---
layout: post
title: January Goals
date: ‘2023-01-01’
categories:
tags:
---

My January goal is to try to make posting to my notebook easier. I would also like to get a better handle at project management. 

January 6 12:52 PM skip line.

Have now moved to using a different application called Working Copy. It has some great features including easily being able to find the file. I've also figured out that I can just say the word that I cannot say because it will do it but anyway I can navigate my cursor. This is cool 😊

Jan 6 12:50pm

OK now I'm getting the hang of it. Without a doubt this is much better. Arguably the most friction list way to make short post updates on a daily/hourly basis great way to capture, notes, ideas, etc..

January 6 12pm

This is another test of using transcription to make a post in this case right now I am still opening the file in the get up app on my phone navigating to the correct file then editing once I commit, it goes right to my notebook


January 6
are you telling me that all I had to do this entire time was opening up the get up app open the file OK maybe I'll type the date January 6, and then I don't even have to type anymore. All I have to do is record a message or I guess another way to phrase that is use speech to text to make a notebook post , this is a game changer! 