project:
  type: website
  output-dir: docs
website:
  title: "Tumbling Oysters"
  site-url: https://sr320.github.io/tumbling-oysters
  search:
    location: navbar
    type: overlay
  navbar:
    right:
      - icon: github
        href: https://github.com/sr320

format:
  html:
    theme:
      dark: darkly
      light: flatly
    code-background: true
    code-copy: true
    code-fold: true
    code-line-numbers: false

editor: visual

