project:
  type: website
  output-dir: docs
website:
  title: "Tumbling Oysters"
  twitter-card: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sr320
      - icon: twitter
        href: https://twitter.com/sr320
format:
  html:
    theme:
      light: flatly
      dark: darkly

editor: visual

