project:
  type: website
  output-dir: docs
website:
  title: "Tumbling Oysters"
  site-url: https://sr320.github.io/tumbling-oysters
  twitter-card: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sr320
      - icon: twitter
        href: https://twitter.com/sr320
format:
  html:
    theme:
      dark: darkly
      light: flatly

editor: visual

