---
title: "New Family on the Block"
subtitle: "Week 4 Reflection"
author: Chris
date: "2023-04-29"
categories: [paper]
---

## Week 4 - Thermal Stress Response in Snails, Mussels, Oysters & Sea Stars

This week we read Gleason & Burton's 2015 [RNA-seq reveals regional differences in transcriptome response to heat stress in the marine snail Chlorostoma funebralis](https://onlinelibrary.wiley.com/doi/abs/10.1111/mec.13047) and found individual papers that cited this one. Gleason and Burton noted that there were regional differences in the same species' response to thermal stress by monitoring the HSP70 and HSP 90 expression in a northern and southern population of snails. Their findings question the molecular mechanisms that induce expression of the HSPs and other molecular chaperones.

I chose a 2021 paper from Clark, Peck and Thyrring, [Resilience in Greenland intertidal Mytilus: The hidden stress defense](https://doi.org/10.1016/j.scitotenv.2020.144366). This paper explores a similar concept as Gleason & Burton with the study species as *Mytilus edulis*. The most interesting finding from this paper was that these mussels were able torecruit a response from a whole different family of HSPs, HSPA12. This is a fascinating concept as this gene family is linked to increased copy number of the gene and the preparedness of *Mytilus* to protect itself from environmental stressors. Essentially, if the mussel is 'primed' it can essentially get ready for the upcoming stressors and manage a defense, it is called hardening. Very cool.

While we all read papers that cited the Gleason & Burton paper, I feel like the findings in this paper are most applicable to my work as contaminants add to an already stressed environment. When faced with dirty water and elevated temperatures it feels bleak to think about the health of the aquatic organisms, but knowing they have defenses that they can harness while we work toward cleaning up our mess it hopeful.
