---
layout: post
title: Reading, Writing and more
date: ‘2023-02-06’
categories: lab meeting
tags: random
---

In preparation for lab meeting, some answer to Chris's queries

## Literature Review
Does your process mirror the tried and true method?

**No**

```
Tried & True Method
Question
Set scope of literature search (date range, specific aspect, keywords, etc.)
Search & Read
Revise question
Read some more
```

How do you catalog/ track your papers?

**Paperpile**

What style of annotation and note taking works best for immediate and/ or long term recall (in your reference manager, not memory explicitly)?

**Only annotation is markup of PDFs.**

Do you keep track of your keyword searches?

**No**

Is an annotated bibliography really the way to go?

**Not really sure what this is**

When do you decide you have enough literature?

**When it feels be search is exhaustive**

## Writing Process
Do you begin writing after your initial analysis, write in small bits throughout, or wait until you’ve completed analysis and visualization?

**Start writing as soon as start methods**

What is your writing process (assuming completed analysis and visualization)?

**? see below**

Do you write methods first, get inspired by the literature and write a killer introduction, make an outline, etc.?

**Methods, Results, Discussion, Introduction, Abstract**

What makes a good collaborative writing partner(s)?

**Regularity in Google Docs, using comments, suggestions, and letter comment be closed by one who writes if not super, super clear.**

What are your biggest stumbling blocks and how do you get around them?

**Writing... Blocking time and just writing, not pretty, flow of ideas, then go back and edit**

What is your weakest writing ability? Your strongest?

**typos, spelling,  .... methods, and selling just below overselling**

Do you write daily?

**Manuscripts?, no**
