---
title: "The Role of DNA Methylation and Context Dependence"
author: "Zach Bengtsson"
date: "2023-05-17"
categories: [post]
toc: true
---

## Primary paper

[**Is There a Relationship between DNA Methylation and Phenotypic Plasticity in Invertebrates?**](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3249382)

TL;DR - Yeah seems like it

**This paper highlights the importance of DNA methylation in invertebrates and suggests that its absence in certain genes contributes to phenotypic variation, which can enhance adaptive potential in fluctuating environments.**

While DNA methylation has been extensively studied in mammals and plants, there is limited knowledge about this mechanism in invertebrates. The relative amount of DNA methylation varies significantly across taxa, with vertebrates exhibiting global methylation, while invertebrates show a wide range of methylation patterns.

In invertebrates, DNA methylation patterns are associated with gene coding regions. Computational analysis has shown that genes predicted to be methylated in the germline have lower genetic diversity compared to unmethylated genes. Experimental studies in invertebrates, such as oysters and bees, have confirmed these findings and revealed that methylated genes are involved in critical biological processes, while unmethylated genes are associated with tissue-specific and inducible expression.

The absence of germline methylation in genes involved in responding to environmental changes is proposed to facilitate phenotypic plasticity and increase adaptive potential. This absence of methylation allows for various transcriptional opportunities, including alternative transcription start sites, increased sequence mutations, and exon skipping. DNA methylation can act as a regulatory mechanism for controlling gene expression and influencing ecologically important traits.

However, there are still unanswered questions regarding the mechanisms underlying the relationship between DNA methylation and transcriptional opportunities in invertebrates. Further research is needed to understand the specific roles of DNA methylation in different invertebrate species and their evolutionary implications.

## The (very brief) paper I chose

[**Without mechanisms, theories and models in insect epigenetics remain a black box**](https://www.sciencedirect.com/science/article/pii/S0168952522001123)

TL; DR - But what do we REALLY know about methylation in insects?

**This review calls for a comprehensive understanding of the functionality and context-dependent roles of DNA methylation systems in insects through mechanistic descriptions, analysis of complex enzymology, and exploration of their specific roles. It highlights the limitations of current knowledge and encourages further research to unravel the intricacies of insect epigenetics.**

The paper emphasizes the need to address the remarkable diversity of epigenomic systems in insects and nematodes by integrating genomic data with biochemical and single-cell-type analyses. It highlights the significant differences in epigenomic modification toolkits across taxa and suggests that they are utilized in a lineage-specific context, reflecting the evolutionary history of organisms. The authors specifically focus on DNA methylation, which exhibits extraordinary diversity in animals, ranging from complete loss to expanded complements of DNMT.

The study raises several unresolved questions regarding the evolutionary origins and organism-specific roles of DNA methylation systems, the transferability of data between different systems, and the distinguishing features of species without DNA methylation. Investigating organisms that have eliminated DNA methylation, such as Diptera, Placozoa, and certain Nematoda, may provide insights into the reasons behind this loss. The authors propose that eutelic or partly eutelic organisms, like Caenorhabditis elegans and tardigrades, eliminated DNA methylation to maintain strict development and enhance genome and transcriptome stability.

The paper also highlights the unique case of DNA methylation in Hymenoptera, focusing on the honey bee. The honey bee's DNA methylation toolkit exhibits variations, including gene duplication and alternative splicing, which may contribute to its phenotypic plasticity. Understanding the mechanistic aspects and functional importance of DNA methylation in insects, particularly in relation to development, behavioral maturation, and restricted gene expression, is crucial.

The study acknowledges that the function of DNA methylation in insects remains poorly understood and emphasizes the need for high-resolution technologies to evaluate its involvement in development and behavioral maturation, especially in the honey bee queen-worker developmental divide. Additionally, the epigenetic control of gene expression in imaginal discs during insect development and the role of nutritional stimuli in reprogramming developmental processes are discussed as important areas of investigation.
