{
  "hash": "fc7e0aab80324d5e8ac30c8d495d16f1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Calcifying Contra\"\ndescription: \"and beyond\"\ncategories: [e5, coral]\n#citation: \ndate: 11-29-2025\nimage: http://gannet.fish.washington.edu/seashell/snaps/Monosnap_Image_2025-11-30_08-27-36.png # finding a good image\nauthor:\n  - name: Steven Roberts\n    url: \n    orcid: 0000-0001-8302-1138\n    affiliation: Professor, UW - School of Aquatic and Fishery Sciences\n    affiliation-url: https://robertslab.info\n  #url:  # self-defined\ndraft: false # setting this to `true` will prevent your post from appearing on your listing page until you're ready!\nformat:\n  html:\n    code-fold: FALSE\n    code-tools: true\n    code-copy: true\n    highlight-style: github\n    code-overflow: wrap\n#runtime: shiny\n---\n\nFirst off in time-series-calcification\n\nhttps://github.com/urol-e5/timeseries-molecular-calcification/blob/main/M-multi-species/scripts/34-biomin-pathway-compare.rmd\n\n![](http://gannet.fish.washington.edu/seashell/snaps/Monosnap_Image_2025-11-30_08-22-16.png) ![ortho-spread](http://gannet.fish.washington.edu/seashell/snaps/Monosnap_Image_2025-11-30_08-23-06.png)\n\n![](http://gannet.fish.washington.edu/seashell/snaps/Monosnap_Image_2025-11-30_08-23-48.png)\n\n![genelevel](http://gannet.fish.washington.edu/seashell/snaps/000010.png) ![](http://gannet.fish.washington.edu/seashell/snaps/Monosnap_Image_2025-11-30_08-25-38.png)\n\n![](http://gannet.fish.washington.edu/seashell/snaps/Monosnap_Image_2025-11-30_08-26-36.png)\n\n# Contra\n\nThen took onto ConTra... with new script\n\n```         \nDuro:ConTra sr320$ python3 code/run_biomin_species_comparison.py                                         ======================================================================\n🧬 CROSS-SPECIES BIOMIN CONTEXT-DEPENDENT ANALYSIS\n======================================================================\nWorkspace: /Users/sr320/GitHub/ConTra\nComparison output: /Users/sr320/GitHub/ConTra/output/biomin_comparison_20251129_144655\n======================================================================\n```\n\n```         \n Using context_dependent_analysis_20251129_192544 for apul\n  Using context_dependent_analysis_20251129_162258 for peve\n  Using context_dependent_analysis_20251129_144655 for ptua\n\n============================================================\nLOADING SPECIES RESULTS\n============================================================\n\n📂 Loading A. pulchra...\n  ✅ Loaded methylation_mirna_context.csv: 33270 rows\n\n📂 Loading P. evermanni...\n  ✅ Loaded methylation_mirna_context.csv: 27150 rows\n\n📂 Loading P. tuahiniensis...\n  ✅ Loaded methylation_mirna_context.csv: 51150 rows\n\n============================================================\nCOMPARING METHYLATION-MIRNA CONTEXT ACROSS SPECIES\n============================================================\n\n📊 Summary:\n  Total unique OGs across all species: 611\n  OGs in 2+ species: 358\n  OGs in all 3 species: 100\n\n✅ Saved comparison table: /Users/sr320/GitHub/ConTra/output/biomin_comparison_20251130_052506/cross_species_methylation_mirna_comparison.csv\n\n🏆 Top 15 Conserved Context-Dependent OGs (in 2+ species):\n   og_id  n_species  mean_context_strength  apul_context_strength  peve_context_strength  ptua_context_strength\nOG_01155          3               1.310726               1.521005               0.996267               1.414906\nOG_02619          3               1.295301               1.468612               1.024492               1.392800\nOG_06119          3               1.236816               0.971755               1.252635               1.486059\nOG_08793          3               1.236346               0.808764               1.450764               1.449511\nOG_05366          3               1.199557               0.939276               1.174450               1.484946\nOG_03291          3               1.199266               1.186752               0.799569               1.611478\nOG_05637          3               1.192262               1.166134               1.165108               1.245543\nOG_01452          3               1.191146               1.526632               0.922735               1.124072\nOG_07153          3               1.174770               0.979025               1.358085               1.187201\nOG_01414          3               1.161650               1.680689               0.775683               1.028577\nOG_01753          3               1.160818               1.140792               1.097454               1.244207\nOG_08663          3               1.138407               0.935220               1.247335               1.232668\nOG_09796          3               1.133137               1.016265               1.074893               1.308253\nOG_04467          3               1.121429               1.075908               1.254588               1.033790\nOG_07892          3               1.113713               1.090661               0.877698               1.372780\n\n============================================================\nGENERATING VISUALIZATIONS\n============================================================\n/Users/sr320/GitHub/ConTra/code/run_biomin_species_comparison.py:397: FutureWarning: \n\nPassing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.\n\n  sns.violinplot(data=strength_df, x='species', y='context_strength',\n✅ Saved comparison plots: /Users/sr320/GitHub/ConTra/output/biomin_comparison_20251130_052506/plots/species_comparison_overview.png\n✅ Saved comparison report: /Users/sr320/GitHub/ConTra/output/biomin_comparison_20251130_052506/cross_species_comparison_report.md\n\n======================================================================\n🎉 CROSS-SPECIES COMPARISON COMPLETE!\n======================================================================\nResults saved to: /Users/sr320/GitHub/ConTra/output/biomin_comparison_20251130_052506\n======================================================================\n```\n\n## **What the script does:**\n\n1.  **Runs analysis on all 3 species** in [full-species-biomin](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html):\n\n    -   A. pulchra (apul)\n\n    -   P. evermanni (peve)\n\n    -   P. tuahiniensis (ptua)\n\n2.  **Extracts OG IDs** from the results using regex to parse formats like:\n\n    -   `\"('OG_13910', 'FUN_002435')\"`\n\n    -   `OG_13910`\n\n3.  **Compares results across species**:\n\n    -   Finds OGs present in 2+ species\n\n    -   Ranks by conservation and context strength\n\n    -   Calculates correlations between species\n\n4.  **Generates outputs**:\n\n    -   `cross_species_methylation_mirna_comparison.csv` - Full comparison table\n\n    -   `plots/species_comparison_overview.png` - 4-panel visualization\n\n    -   `cross_species_comparison_report.md` - Summary report\n\n------------------------------------------------------------------------\n\n# Cross-Species Biomin Context-Dependent Analysis Comparison\n\n**Generated:** 2025-11-30 05:25:07\n\n## Overview\n\nThis report compares context-dependent regulatory interactions across three coral species:\n\n-   **A. pulchra** (`apul`)\n-   **P. evermanni** (`peve`)\n-   **P. tuahiniensis** (`ptua`)\n\n## Per-Species Summary\n\n### A. pulchra (apul)\n\n-   Total methylation-miRNA interactions: 33270\n-   Context-dependent interactions: 3039\n-   Mean context strength: 0.311\n-   Unique OGs: 334\n\n### P. evermanni (peve)\n\n-   Total methylation-miRNA interactions: 27150\n-   Context-dependent interactions: 3935\n-   Mean context strength: 0.371\n-   Unique OGs: 309\n\n### P. tuahiniensis (ptua)\n\n-   Total methylation-miRNA interactions: 51150\n-   Context-dependent interactions: 8765\n-   Mean context strength: 0.346\n-   Unique OGs: 474\n\n## Cross-Species Conservation\n\n-   **Total unique OGs:** 611\n-   **OGs in 2+ species:** 358 (58.6%)\n-   **OGs in all 3 species:** 100 (16.4%)\n     \n\n## Interpretation\n\nOGs (orthologous groups) that show context-dependent regulation in multiple species suggest:\n\n1.  **Conserved regulatory mechanisms** - These genes may have fundamental roles where regulation is evolutionarily maintained\n2.  **Robust biological signals** - Conservation across species reduces the likelihood of false positives\n3.  **Candidates for functional validation** - These genes are high-priority targets for experimental follow-up\n\n## Files Generated\n\n-   `cross_species_methylation_mirna_comparison.csv` - Full comparison table\n-   `plots/species_comparison_overview.png` - Visualization of cross-species patterns\n-   `cross_species_comparison_report.md` - This report\n\n------------------------------------------------------------------------\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.1     ✔ stringr   1.5.2\n✔ ggplot2   4.0.0     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.1.0     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(reactable)\nlibrary(htmltools)\n\nurl <- \"https://gannet.fish.washington.edu/v1_web/owlshell/bu-github/ConTra/output/biomin_comparison_20251130_052506/cross_species_methylation_mirna_comparison.csv\"\ndf <- read_csv(url, show_col_types = FALSE)\n\n# Format all numeric columns to 2 digits after decimal\ndf_fmt <- df %>%\n  mutate(across(where(is.numeric), ~ sprintf(\"%.2f\", .x)))\n\nreactable(\n  df_fmt,\n  searchable = TRUE,\n  filterable = TRUE,\n  pagination = TRUE,\n  highlight = TRUE,\n  striped = TRUE,\n  defaultPageSize = 20,\n  sortable = TRUE,\n  theme = reactable::reactableTheme(\n    highlightColor = \"#EAF2F8\"\n  )\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"reactable html-widget html-fill-item\" id=\"htmlwidget-eb4ce03d416dcb25c4cf\" style=\"width:auto;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-eb4ce03d416dcb25c4cf\">{\"x\":{\"tag\":{\"name\":\"Reactable\",\"attribs\":{\"data\":{\"og_id\":[\"OG_01155\",\"OG_02619\",\"OG_06119\",\"OG_08793\",\"OG_05366\",\"OG_03291\",\"OG_05637\",\"OG_01452\",\"OG_07153\",\"OG_01414\",\"OG_01753\",\"OG_08663\",\"OG_09796\",\"OG_04467\",\"OG_07892\",\"OG_07150\",\"OG_02190\",\"OG_00355\",\"OG_06712\",\"OG_08849\",\"OG_09106\",\"OG_08920\",\"OG_08192\",\"OG_06616\",\"OG_04799\",\"OG_09596\",\"OG_01177\",\"OG_09310\",\"OG_05718\",\"OG_01630\",\"OG_06592\",\"OG_10121\",\"OG_03673\",\"OG_01611\",\"OG_07252\",\"OG_10205\",\"OG_09174\",\"OG_06955\",\"OG_01384\",\"OG_03484\",\"OG_00752\",\"OG_03330\",\"OG_08259\",\"OG_06999\",\"OG_00297\",\"OG_04165\",\"OG_03857\",\"OG_02666\",\"OG_07958\",\"OG_05666\",\"OG_06908\",\"OG_06430\",\"OG_07389\",\"OG_07404\",\"OG_07821\",\"OG_00171\",\"OG_03628\",\"OG_02090\",\"OG_08545\",\"OG_02124\",\"OG_08842\",\"OG_06247\",\"OG_08874\",\"OG_09511\",\"OG_06599\",\"OG_01023\",\"OG_09455\",\"OG_01317\",\"OG_04789\",\"OG_03429\",\"OG_02088\",\"OG_05819\",\"OG_04694\",\"OG_08144\",\"OG_05514\",\"OG_05304\",\"OG_10004\",\"OG_10039\",\"OG_00176\",\"OG_03451\",\"OG_04243\",\"OG_00460\",\"OG_06004\",\"OG_06655\",\"OG_00378\",\"OG_02176\",\"OG_09024\",\"OG_06775\",\"OG_09003\",\"OG_06198\",\"OG_02317\",\"OG_09423\",\"OG_02148\",\"OG_05952\",\"OG_00466\",\"OG_05856\",\"OG_01748\",\"OG_05713\",\"OG_06875\",\"OG_07042\",\"OG_06610\",\"OG_11813\",\"OG_05250\",\"OG_13910\",\"OG_11360\",\"OG_02000\",\"OG_15303\",\"OG_02408\",\"OG_05303\",\"OG_10758\",\"OG_14180\",\"OG_02537\",\"OG_14711\",\"OG_15374\",\"OG_10515\",\"OG_05010\",\"OG_14803\",\"OG_16627\",\"OG_13792\",\"OG_12611\",\"OG_06152\",\"OG_06998\",\"OG_04756\",\"OG_00643\",\"OG_11957\",\"OG_10472\",\"OG_11234\",\"OG_02163\",\"OG_02220\",\"OG_18223\",\"OG_16000\",\"OG_09598\",\"OG_01121\",\"OG_12050\",\"OG_08331\",\"OG_13882\",\"OG_05749\",\"OG_12722\",\"OG_02186\",\"OG_14612\",\"OG_15877\",\"OG_13886\",\"OG_00842\",\"OG_08528\",\"OG_07508\",\"OG_14257\",\"OG_05717\",\"OG_12990\",\"OG_10936\",\"OG_00807\",\"OG_07620\",\"OG_10522\",\"OG_15086\",\"OG_08622\",\"OG_06279\",\"OG_14674\",\"OG_13201\",\"OG_18057\",\"OG_14804\",\"OG_14279\",\"OG_14623\",\"OG_13877\",\"OG_03288\",\"OG_11381\",\"OG_17186\",\"OG_04698\",\"OG_14915\",\"OG_08083\",\"OG_04651\",\"OG_18058\",\"OG_06373\",\"OG_04515\",\"OG_08856\",\"OG_12320\",\"OG_05950\",\"OG_10814\",\"OG_11907\",\"OG_14262\",\"OG_15009\",\"OG_05498\",\"OG_13451\",\"OG_10251\",\"OG_16489\",\"OG_04327\",\"OG_16307\",\"OG_11964\",\"OG_16092\",\"OG_02012\",\"OG_12880\",\"OG_15020\",\"OG_09897\",\"OG_06719\",\"OG_08145\",\"OG_14322\",\"OG_06158\",\"OG_15375\",\"OG_17157\",\"OG_11984\",\"OG_16573\",\"OG_08768\",\"OG_12878\",\"OG_02184\",\"OG_08878\",\"OG_03856\",\"OG_10811\",\"OG_14140\",\"OG_15087\",\"OG_04723\",\"OG_12805\",\"OG_01117\",\"OG_13197\",\"OG_01147\",\"OG_14037\",\"OG_00514\",\"OG_13016\",\"OG_01353\",\"OG_07641\",\"OG_01608\",\"OG_08497\",\"OG_12646\",\"OG_14189\",\"OG_18262\",\"OG_08432\",\"OG_07531\",\"OG_00246\",\"OG_13026\",\"OG_03269\",\"OG_06717\",\"OG_07183\",\"OG_08096\",\"OG_14382\",\"OG_11852\",\"OG_06754\",\"OG_14540\",\"OG_11839\",\"OG_17479\",\"OG_13154\",\"OG_13050\",\"OG_14563\",\"OG_18258\",\"OG_10109\",\"OG_14793\",\"OG_14500\",\"OG_17098\",\"OG_14615\",\"OG_08639\",\"OG_01579\",\"OG_06234\",\"OG_00510\",\"OG_14206\",\"OG_01724\",\"OG_11359\",\"OG_01475\",\"OG_15334\",\"OG_11833\",\"OG_11642\",\"OG_09986\",\"OG_11019\",\"OG_08717\",\"OG_06711\",\"OG_15550\",\"OG_15459\",\"OG_03289\",\"OG_01781\",\"OG_10988\",\"OG_17286\",\"OG_02102\",\"OG_11870\",\"OG_03671\",\"OG_08658\",\"OG_13066\",\"OG_05087\",\"OG_01758\",\"OG_10055\",\"OG_14038\",\"OG_10759\",\"OG_11084\",\"OG_10675\",\"OG_16539\",\"OG_04209\",\"OG_02924\",\"OG_11307\",\"OG_16856\",\"OG_04115\",\"OG_16980\",\"OG_00572\",\"OG_14627\",\"OG_06101\",\"OG_01354\",\"OG_11423\",\"OG_13916\",\"OG_09657\",\"OG_18229\",\"OG_03267\",\"OG_06181\",\"OG_03850\",\"OG_00030\",\"OG_12318\",\"OG_05121\",\"OG_16011\",\"OG_14276\",\"OG_04443\",\"OG_16192\",\"OG_14710\",\"OG_03626\",\"OG_06931\",\"OG_15383\",\"OG_10938\",\"OG_10367\",\"OG_14505\",\"OG_06954\",\"OG_10579\",\"OG_02690\",\"OG_00632\",\"OG_01999\",\"OG_01223\",\"OG_01312\",\"OG_06922\",\"OG_08077\",\"OG_12248\",\"OG_12286\",\"OG_09487\",\"OG_12683\",\"OG_14094\",\"OG_16585\",\"OG_12888\",\"OG_14380\",\"OG_16862\",\"OG_17751\",\"OG_17245\",\"OG_16158\",\"OG_14626\",\"OG_09424\",\"OG_12162\",\"OG_04537\",\"OG_03298\",\"OG_17389\",\"OG_01489\",\"OG_16209\",\"OG_14100\",\"OG_08271\",\"OG_15312\",\"OG_06670\",\"OG_12166\",\"OG_16592\",\"OG_09806\",\"OG_05568\",\"OG_11983\",\"OG_08143\",\"OG_07772\",\"OG_02358\",\"OG_07000\",\"OG_17015\",\"OG_12165\",\"OG_00298\",\"OG_03780\",\"OG_17012\",\"OG_13428\",\"OG_07265\",\"OG_14547\",\"OG_10509\",\"OG_12496\",\"OG_12612\",\"OG_12102\",\"OG_12406\",\"OG_12447\",\"OG_12616\",\"OG_16747\",\"OG_15816\",\"OG_16145\",\"OG_13032\",\"OG_10818\",\"OG_17106\",\"OG_10355\",\"OG_14588\",\"OG_08347\",\"OG_11365\",\"OG_11379\",\"OG_14381\",\"OG_11429\",\"OG_04247\",\"OG_11038\",\"OG_09969\",\"OG_13481\",\"OG_10838\",\"OG_10516\",\"OG_16122\",\"OG_10008\",\"OG_09896\",\"OG_12125\",\"OG_10480\",\"OG_10183\",\"OG_10937\",\"OG_13239\",\"OG_10520\",\"OG_12785\",\"OG_11156\",\"OG_10267\",\"OG_00843\",\"OG_16469\",\"OG_03268\",\"OG_11653\",\"OG_11292\",\"OG_12007\",\"OG_17347\",\"OG_10475\",\"OG_13033\",\"OG_14685\",\"OG_15544\",\"OG_15070\",\"OG_13684\",\"OG_11794\",\"OG_15594\",\"OG_16944\",\"OG_10007\",\"OG_00314\",\"OG_16389\",\"OG_12331\",\"OG_18159\",\"OG_12475\",\"OG_05210\",\"OG_15754\",\"OG_15604\",\"OG_13091\",\"OG_15021\",\"OG_14455\",\"OG_15551\",\"OG_09597\",\"OG_09942\",\"OG_15648\",\"OG_13215\",\"OG_04331\",\"OG_11380\",\"OG_16359\",\"OG_16883\",\"OG_07394\",\"OG_16383\",\"OG_17150\",\"OG_07331\",\"OG_10002\",\"OG_15121\",\"OG_14681\",\"OG_15644\",\"OG_12476\",\"OG_16485\",\"OG_13465\",\"OG_12107\",\"OG_10523\",\"OG_06236\",\"OG_12371\",\"OG_16279\",\"OG_13466\",\"OG_17806\",\"OG_04514\",\"OG_15815\",\"OG_12032\",\"OG_12046\",\"OG_11420\",\"OG_15089\",\"OG_12647\",\"OG_10681\",\"OG_14790\",\"OG_01568\",\"OG_16544\",\"OG_14407\",\"OG_13013\",\"OG_11899\",\"OG_15906\",\"OG_12242\",\"OG_17596\",\"OG_11017\",\"OG_02070\",\"OG_15796\",\"OG_07807\",\"OG_02146\",\"OG_11541\",\"OG_14066\",\"OG_06384\",\"OG_15137\",\"OG_07330\",\"OG_03270\",\"OG_02439\",\"OG_13149\",\"OG_01486\",\"OG_12844\",\"OG_01747\",\"OG_00305\",\"OG_00430\",\"OG_12160\",\"OG_11171\",\"OG_17591\",\"OG_00302\",\"OG_14514\",\"OG_12108\",\"OG_13484\",\"OG_12889\",\"OG_10907\",\"OG_17285\",\"OG_12019\",\"OG_10815\",\"OG_18263\",\"OG_15682\",\"OG_02316\",\"OG_17600\",\"OG_14012\",\"OG_17045\",\"OG_04538\",\"OG_14792\",\"OG_10584\",\"OG_13190\",\"OG_05875\",\"OG_12952\",\"OG_17058\",\"OG_02967\",\"OG_14994\",\"OG_15060\",\"OG_11215\",\"OG_13059\",\"OG_05874\",\"OG_11296\",\"OG_17533\",\"OG_16586\",\"OG_01981\",\"OG_05308\",\"OG_04238\",\"OG_17027\",\"OG_15617\",\"OG_15140\",\"OG_17497\",\"OG_11831\",\"OG_17666\",\"OG_09638\",\"OG_13153\",\"OG_12163\",\"OG_17646\",\"OG_02260\",\"OG_11245\",\"OG_13191\",\"OG_18275\",\"OG_16159\",\"OG_17124\",\"OG_10274\",\"OG_07822\",\"OG_11291\",\"OG_13685\",\"OG_14408\",\"OG_15831\",\"OG_13594\",\"OG_13211\",\"OG_11419\",\"OG_10450\",\"OG_10265\",\"OG_13031\",\"OG_01277\",\"OG_14889\",\"OG_12109\",\"OG_18078\",\"OG_11644\",\"OG_18224\",\"OG_14156\",\"OG_12424\",\"OG_14158\",\"OG_04560\",\"OG_18118\",\"OG_16654\",\"OG_12568\",\"OG_17739\",\"OG_12518\",\"OG_02935\",\"OG_15759\",\"OG_16380\",\"OG_12837\",\"OG_18325\",\"OG_17961\",\"OG_13334\",\"OG_15462\",\"OG_01727\",\"OG_12927\",\"OG_15208\",\"OG_12972\",\"OG_10812\",\"OG_09486\",\"OG_11762\",\"OG_07836\",\"OG_17800\",\"OG_02149\",\"OG_10525\",\"OG_16879\",\"OG_08914\",\"OG_02219\",\"OG_17222\",\"OG_17483\",\"OG_10350\",\"OG_04547\",\"OG_06607\",\"OG_17176\",\"OG_12560\",\"OG_17014\",\"OG_18285\",\"OG_16707\",\"OG_16139\",\"OG_16270\",\"OG_05228\",\"OG_16789\",\"OG_05367\",\"OG_11812\",\"OG_11074\",\"OG_12645\",\"OG_16665\",\"OG_17453\",\"OG_14295\"],\"n_species\":[\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"3.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"2.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\"],\"apul_context_strength\":[\"1.52\",\"1.47\",\"0.97\",\"0.81\",\"0.94\",\"1.19\",\"1.17\",\"1.53\",\"0.98\",\"1.68\",\"1.14\",\"0.94\",\"1.02\",\"1.08\",\"1.09\",\"0.80\",\"1.23\",\"1.06\",\"1.35\",\"1.01\",\"0.68\",\"1.77\",\"0.98\",\"0.70\",\"0.97\",\"0.98\",\"1.18\",\"0.89\",\"0.84\",\"0.75\",\"0.97\",\"1.30\",\"1.30\",\"1.26\",\"1.21\",\"1.17\",\"0.48\",\"0.91\",\"1.07\",\"1.03\",\"0.70\",\"1.11\",\"0.61\",\"0.98\",\"0.80\",\"0.90\",\"0.95\",\"0.39\",\"0.81\",\"0.70\",\"0.68\",\"1.04\",\"1.02\",\"0.85\",\"0.60\",\"0.77\",\"0.98\",\"1.30\",\"0.72\",\"0.73\",\"0.97\",\"0.57\",\"0.99\",\"0.93\",\"0.67\",\"0.80\",\"1.26\",\"0.98\",\"0.69\",\"0.40\",\"0.89\",\"0.91\",\"1.03\",\"0.94\",\"0.81\",\"1.13\",\"0.87\",\"0.89\",\"0.26\",\"1.05\",\"0.64\",\"0.72\",\"0.90\",\"0.89\",\"0.51\",\"1.06\",\"0.92\",\"0.64\",\"0.95\",\"0.91\",\"0.99\",\"0.62\",\"0.72\",\"0.55\",\"0.33\",\"0.73\",\"0.67\",\"0.42\",\"0.40\",\"0.59\",\"1.27\",\"NA\",\"1.38\",\"1.56\",\"NA\",\"NA\",\"1.58\",\"1.18\",\"0.92\",\"NA\",\"1.45\",\"1.81\",\"1.01\",\"1.14\",\"NA\",\"1.15\",\"1.34\",\"1.29\",\"1.15\",\"NA\",\"1.02\",\"NA\",\"1.31\",\"1.19\",\"NA\",\"NA\",\"NA\",\"0.88\",\"1.01\",\"1.37\",\"1.19\",\"NA\",\"1.51\",\"NA\",\"0.88\",\"1.18\",\"1.13\",\"NA\",\"NA\",\"1.20\",\"1.24\",\"1.05\",\"0.83\",\"1.11\",\"0.85\",\"0.96\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.19\",\"1.49\",\"NA\",\"1.17\",\"NA\",\"1.02\",\"1.56\",\"1.27\",\"1.29\",\"1.02\",\"0.82\",\"NA\",\"1.19\",\"NA\",\"1.21\",\"1.30\",\"0.73\",\"1.05\",\"1.17\",\"1.42\",\"1.19\",\"NA\",\"1.03\",\"NA\",\"NA\",\"1.16\",\"0.97\",\"1.09\",\"NA\",\"0.88\",\"1.13\",\"NA\",\"1.08\",\"NA\",\"0.96\",\"NA\",\"NA\",\"0.87\",\"0.85\",\"NA\",\"1.36\",\"1.13\",\"1.25\",\"0.99\",\"1.05\",\"NA\",\"0.96\",\"1.15\",\"NA\",\"0.94\",\"1.29\",\"0.85\",\"NA\",\"0.86\",\"0.69\",\"1.60\",\"NA\",\"0.53\",\"NA\",\"NA\",\"0.73\",\"1.05\",\"NA\",\"NA\",\"1.15\",\"1.20\",\"0.99\",\"NA\",\"0.91\",\"0.85\",\"NA\",\"0.86\",\"NA\",\"NA\",\"0.66\",\"1.20\",\"NA\",\"0.76\",\"0.66\",\"NA\",\"1.00\",\"0.88\",\"NA\",\"0.85\",\"NA\",\"NA\",\"1.20\",\"1.25\",\"1.11\",\"1.19\",\"1.08\",\"1.25\",\"1.39\",\"0.95\",\"0.92\",\"0.62\",\"0.87\",\"0.79\",\"0.51\",\"NA\",\"0.75\",\"0.75\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.91\",\"0.51\",\"1.05\",\"0.64\",\"NA\",\"NA\",\"NA\",\"0.69\",\"0.74\",\"NA\",\"0.94\",\"NA\",\"NA\",\"0.60\",\"0.82\",\"0.67\",\"0.79\",\"NA\",\"NA\",\"NA\",\"0.57\",\"0.62\",\"1.05\",\"NA\",\"0.85\",\"NA\",\"0.97\",\"0.99\",\"0.84\",\"NA\",\"1.11\",\"NA\",\"0.91\",\"0.93\",\"0.54\",\"NA\",\"1.26\",\"0.57\",\"NA\",\"NA\",\"NA\",\"1.39\",\"0.58\",\"0.61\",\"1.26\",\"0.78\",\"NA\",\"0.93\",\"0.46\",\"NA\",\"NA\",\"0.98\",\"0.92\",\"NA\",\"0.49\",\"0.50\",\"0.89\",\"0.90\",\"0.76\",\"NA\",\"0.75\",\"NA\",\"NA\",\"0.64\",\"NA\",\"0.77\",\"0.90\",\"NA\",\"0.70\",\"0.77\",\"0.92\",\"0.46\",\"0.65\",\"1.03\",\"0.69\",\"NA\",\"0.57\",\"0.42\",\"0.60\",\"0.84\",\"0.73\",\"0.29\",\"NA\",\"0.65\",\"NA\",\"NA\",\"0.77\",\"0.49\",\"0.72\",\"NA\",\"0.55\",\"0.61\",\"0.42\",\"0.40\",\"0.57\",\"NA\",\"0.53\",\"0.10\",\"0.95\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.48\",\"1.47\",\"1.44\",\"NA\",\"NA\",\"1.40\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.37\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.30\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.28\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.24\",\"1.24\",\"NA\",\"NA\",\"1.23\",\"NA\",\"1.23\",\"NA\",\"NA\",\"1.21\",\"1.21\",\"NA\",\"1.21\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.20\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.19\",\"NA\",\"1.19\",\"1.18\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.16\",\"NA\",\"1.16\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.14\",\"NA\",\"NA\",\"1.14\",\"1.13\",\"NA\",\"NA\",\"NA\",\"1.13\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.11\",\"NA\",\"NA\",\"NA\",\"1.10\",\"NA\",\"1.09\",\"NA\",\"NA\",\"1.08\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.02\",\"NA\",\"NA\",\"1.01\",\"1.01\",\"NA\",\"1.01\",\"1.01\",\"1.01\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.97\",\"0.97\",\"0.96\",\"NA\",\"NA\",\"0.96\",\"0.96\",\"NA\",\"0.96\",\"NA\",\"0.95\",\"NA\",\"NA\",\"NA\",\"0.94\",\"0.94\",\"NA\",\"NA\",\"0.93\",\"NA\",\"NA\",\"NA\",\"0.92\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.88\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.83\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.81\",\"0.81\",\"NA\",\"0.80\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.72\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.70\",\"NA\",\"NA\",\"0.66\",\"NA\",\"NA\",\"0.64\",\"NA\",\"NA\",\"0.61\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.51\",\"0.51\",\"NA\",\"0.51\",\"NA\",\"NA\",\"0.48\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.32\",\"0.27\",\"0.14\"],\"apul_context_dependent\":[false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false,true,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,true,null,false,false,null,null,false,false,false,null,true,true,false,false,null,false,true,false,false,null,false,null,false,false,null,null,null,false,false,true,false,null,false,null,true,true,false,null,null,true,false,false,false,false,false,false,null,null,null,null,null,null,true,false,null,false,null,false,false,false,false,false,false,null,false,null,false,false,false,false,false,false,false,null,false,null,null,true,false,false,null,false,false,null,false,null,false,null,null,false,false,null,false,false,false,false,false,null,false,false,null,false,false,false,null,true,false,true,null,false,null,null,false,false,null,null,false,false,false,null,false,true,null,false,null,null,true,false,null,false,false,null,false,false,null,false,null,null,true,false,true,false,false,false,false,false,false,false,false,false,false,null,false,false,null,null,null,null,false,false,false,false,null,null,null,false,false,null,false,null,null,false,false,false,true,null,null,null,false,false,true,null,false,null,true,false,false,null,false,null,false,false,false,null,false,false,null,null,null,true,false,false,false,false,null,false,false,null,null,false,false,null,false,false,false,false,false,null,false,null,null,false,null,false,false,null,false,false,false,true,false,false,false,null,false,false,false,false,false,false,null,false,null,null,false,false,false,null,false,false,false,false,false,null,false,false,false,null,null,null,null,null,null,null,null,null,null,false,false,true,null,null,true,null,null,null,null,null,null,null,false,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,false,null,null,null,null,false,null,null,null,null,null,null,null,false,false,null,null,false,null,false,null,null,true,false,null,false,null,null,null,null,false,null,null,null,null,false,null,false,false,null,null,null,null,true,null,false,null,null,null,null,null,true,null,null,false,false,null,null,null,false,null,null,null,null,false,null,null,null,false,null,true,null,null,false,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,false,null,null,true,true,null,false,false,true,null,null,null,null,null,null,null,null,null,null,null,null,null,null,false,false,false,null,null,false,false,null,false,null,false,null,null,null,false,false,null,null,false,null,null,null,false,null,null,null,null,null,null,null,null,false,null,null,null,null,null,null,false,null,null,null,null,true,false,null,true,null,null,null,null,null,null,false,null,null,null,null,false,null,null,false,null,null,false,null,null,false,null,null,null,null,null,null,null,null,null,false,false,null,false,null,null,false,null,null,null,null,false,true,true],\"apul_improvement\":[\"0.05\",\"0.00\",\"0.01\",\"0.01\",\"0.02\",\"0.01\",\"0.00\",\"0.26\",\"0.00\",\"0.02\",\"0.03\",\"0.01\",\"0.01\",\"0.00\",\"0.01\",\"0.00\",\"0.06\",\"0.00\",\"0.03\",\"0.00\",\"0.01\",\"0.02\",\"0.01\",\"0.17\",\"0.00\",\"0.01\",\"0.00\",\"0.00\",\"0.00\",\"0.01\",\"0.04\",\"0.08\",\"0.00\",\"0.05\",\"0.00\",\"0.06\",\"0.00\",\"0.04\",\"0.01\",\"0.04\",\"0.04\",\"0.01\",\"0.00\",\"0.00\",\"0.03\",\"0.00\",\"0.00\",\"0.07\",\"0.02\",\"0.01\",\"0.03\",\"0.11\",\"0.00\",\"0.04\",\"0.00\",\"0.02\",\"0.00\",\"0.00\",\"0.00\",\"0.05\",\"0.01\",\"0.01\",\"0.04\",\"0.00\",\"0.03\",\"0.00\",\"0.01\",\"0.06\",\"0.00\",\"0.01\",\"0.08\",\"0.02\",\"0.01\",\"0.04\",\"0.01\",\"0.00\",\"0.02\",\"0.00\",\"0.00\",\"0.00\",\"0.13\",\"0.08\",\"0.01\",\"0.00\",\"0.00\",\"0.01\",\"0.05\",\"0.01\",\"0.00\",\"0.00\",\"0.03\",\"0.00\",\"0.08\",\"0.00\",\"0.00\",\"0.01\",\"0.00\",\"0.00\",\"0.01\",\"0.00\",\"0.09\",\"NA\",\"0.01\",\"0.00\",\"NA\",\"NA\",\"0.00\",\"0.00\",\"0.04\",\"NA\",\"0.10\",\"0.04\",\"0.00\",\"0.01\",\"NA\",\"0.00\",\"0.05\",\"0.00\",\"0.01\",\"NA\",\"0.00\",\"NA\",\"0.01\",\"0.00\",\"NA\",\"NA\",\"NA\",\"0.00\",\"0.02\",\"0.07\",\"0.01\",\"NA\",\"0.02\",\"NA\",\"0.08\",\"0.15\",\"0.00\",\"NA\",\"NA\",\"0.15\",\"0.04\",\"0.03\",\"0.05\",\"0.02\",\"0.01\",\"0.03\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.09\",\"0.03\",\"NA\",\"0.00\",\"NA\",\"0.01\",\"0.00\",\"0.01\",\"0.01\",\"0.00\",\"0.01\",\"NA\",\"0.02\",\"NA\",\"0.00\",\"0.00\",\"0.03\",\"0.01\",\"0.00\",\"0.04\",\"0.01\",\"NA\",\"0.00\",\"NA\",\"NA\",\"0.07\",\"0.02\",\"0.02\",\"NA\",\"0.00\",\"0.00\",\"NA\",\"0.00\",\"NA\",\"0.01\",\"NA\",\"NA\",\"0.00\",\"0.00\",\"NA\",\"0.05\",\"0.00\",\"0.01\",\"0.01\",\"0.01\",\"NA\",\"0.00\",\"0.00\",\"NA\",\"0.00\",\"0.01\",\"0.05\",\"NA\",\"0.06\",\"0.00\",\"0.13\",\"NA\",\"0.03\",\"NA\",\"NA\",\"0.03\",\"0.00\",\"NA\",\"NA\",\"0.00\",\"0.01\",\"0.00\",\"NA\",\"0.05\",\"0.09\",\"NA\",\"0.01\",\"NA\",\"NA\",\"0.09\",\"0.00\",\"NA\",\"0.01\",\"0.06\",\"NA\",\"0.02\",\"0.00\",\"NA\",\"0.03\",\"NA\",\"NA\",\"0.05\",\"0.02\",\"0.03\",\"0.03\",\"0.01\",\"0.00\",\"0.01\",\"0.04\",\"0.02\",\"0.02\",\"0.00\",\"0.04\",\"0.01\",\"NA\",\"0.01\",\"0.02\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.00\",\"0.00\",\"0.01\",\"0.00\",\"NA\",\"NA\",\"NA\",\"0.00\",\"0.01\",\"NA\",\"0.00\",\"NA\",\"NA\",\"0.00\",\"0.01\",\"0.01\",\"0.08\",\"NA\",\"NA\",\"NA\",\"0.00\",\"0.00\",\"0.04\",\"NA\",\"0.00\",\"NA\",\"0.02\",\"0.00\",\"0.01\",\"NA\",\"0.01\",\"NA\",\"0.01\",\"0.00\",\"0.06\",\"NA\",\"0.01\",\"0.01\",\"NA\",\"NA\",\"NA\",\"0.04\",\"0.00\",\"0.01\",\"0.00\",\"0.00\",\"NA\",\"0.03\",\"0.00\",\"NA\",\"NA\",\"0.01\",\"0.03\",\"NA\",\"0.01\",\"0.01\",\"0.01\",\"0.04\",\"0.00\",\"NA\",\"0.03\",\"NA\",\"NA\",\"0.02\",\"NA\",\"0.01\",\"0.00\",\"NA\",\"0.01\",\"0.02\",\"0.00\",\"0.06\",\"0.00\",\"0.01\",\"0.02\",\"NA\",\"0.01\",\"0.05\",\"0.04\",\"0.02\",\"0.02\",\"0.00\",\"NA\",\"0.00\",\"NA\",\"NA\",\"0.00\",\"0.00\",\"0.00\",\"NA\",\"0.00\",\"0.00\",\"0.00\",\"0.02\",\"0.00\",\"NA\",\"0.01\",\"0.02\",\"0.00\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.02\",\"0.01\",\"0.10\",\"NA\",\"NA\",\"0.06\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.03\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.00\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.01\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.00\",\"0.02\",\"NA\",\"NA\",\"0.00\",\"NA\",\"0.00\",\"NA\",\"NA\",\"0.10\",\"0.01\",\"NA\",\"0.02\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.00\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.00\",\"NA\",\"0.02\",\"0.04\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.05\",\"NA\",\"0.00\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.05\",\"NA\",\"NA\",\"0.00\",\"0.00\",\"NA\",\"NA\",\"NA\",\"0.00\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.01\",\"NA\",\"NA\",\"NA\",\"0.00\",\"NA\",\"0.09\",\"NA\",\"NA\",\"0.01\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.03\",\"NA\",\"NA\",\"0.13\",\"0.10\",\"NA\",\"0.00\",\"0.00\",\"0.07\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.01\",\"0.00\",\"0.00\",\"NA\",\"NA\",\"0.00\",\"0.01\",\"NA\",\"0.01\",\"NA\",\"0.01\",\"NA\",\"NA\",\"NA\",\"0.02\",\"0.00\",\"NA\",\"NA\",\"0.00\",\"NA\",\"NA\",\"NA\",\"0.02\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.01\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.02\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.09\",\"0.00\",\"NA\",\"0.10\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.00\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.00\",\"NA\",\"NA\",\"0.00\",\"NA\",\"NA\",\"0.00\",\"NA\",\"NA\",\"0.00\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.00\",\"0.06\",\"NA\",\"0.00\",\"NA\",\"NA\",\"0.01\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.01\",\"0.02\",\"0.03\"],\"apul_r2\":[\"0.55\",\"0.60\",\"0.56\",\"0.62\",\"0.50\",\"0.71\",\"0.56\",\"0.66\",\"0.58\",\"0.52\",\"0.69\",\"0.75\",\"0.59\",\"0.52\",\"0.48\",\"0.69\",\"0.70\",\"0.52\",\"0.68\",\"0.68\",\"0.42\",\"0.57\",\"0.48\",\"0.70\",\"0.62\",\"0.48\",\"0.81\",\"0.73\",\"0.58\",\"0.65\",\"0.73\",\"0.80\",\"0.70\",\"0.64\",\"0.63\",\"0.76\",\"0.63\",\"0.54\",\"0.48\",\"0.65\",\"0.51\",\"0.72\",\"0.55\",\"0.59\",\"0.47\",\"0.69\",\"0.54\",\"0.62\",\"0.56\",\"0.47\",\"0.55\",\"0.52\",\"0.50\",\"0.64\",\"0.54\",\"0.46\",\"0.53\",\"0.61\",\"0.41\",\"0.50\",\"0.68\",\"0.56\",\"0.58\",\"0.49\",\"0.53\",\"0.56\",\"0.56\",\"0.66\",\"0.46\",\"0.49\",\"0.68\",\"0.51\",\"0.56\",\"0.53\",\"0.45\",\"0.61\",\"0.58\",\"0.45\",\"0.60\",\"0.53\",\"0.68\",\"0.53\",\"0.61\",\"0.66\",\"0.60\",\"0.66\",\"0.46\",\"0.43\",\"0.43\",\"0.51\",\"0.50\",\"0.48\",\"0.55\",\"0.88\",\"0.51\",\"0.49\",\"0.50\",\"0.47\",\"0.46\",\"0.44\",\"0.47\",\"NA\",\"0.72\",\"0.50\",\"NA\",\"NA\",\"0.54\",\"0.72\",\"0.59\",\"NA\",\"0.79\",\"0.77\",\"0.68\",\"0.64\",\"NA\",\"0.62\",\"0.70\",\"0.71\",\"0.63\",\"NA\",\"0.59\",\"NA\",\"0.61\",\"0.97\",\"NA\",\"NA\",\"NA\",\"0.46\",\"0.55\",\"0.58\",\"0.58\",\"NA\",\"0.53\",\"NA\",\"0.56\",\"0.60\",\"0.67\",\"NA\",\"NA\",\"0.60\",\"0.62\",\"0.52\",\"0.56\",\"0.55\",\"0.48\",\"0.70\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.59\",\"0.58\",\"NA\",\"0.58\",\"NA\",\"0.78\",\"0.72\",\"0.52\",\"0.53\",\"0.69\",\"0.57\",\"NA\",\"0.87\",\"NA\",\"0.88\",\"0.44\",\"0.48\",\"0.66\",\"0.50\",\"0.52\",\"0.67\",\"NA\",\"0.60\",\"NA\",\"NA\",\"0.74\",\"0.58\",\"0.53\",\"NA\",\"0.78\",\"0.63\",\"NA\",\"0.54\",\"NA\",\"0.51\",\"NA\",\"NA\",\"0.51\",\"0.63\",\"NA\",\"0.57\",\"0.62\",\"0.77\",\"0.64\",\"0.65\",\"NA\",\"0.55\",\"0.71\",\"NA\",\"0.42\",\"0.80\",\"0.51\",\"NA\",\"0.83\",\"0.60\",\"0.55\",\"NA\",\"0.64\",\"NA\",\"NA\",\"0.48\",\"0.48\",\"NA\",\"NA\",\"0.73\",\"0.64\",\"0.55\",\"NA\",\"0.63\",\"0.54\",\"NA\",\"0.62\",\"NA\",\"NA\",\"0.69\",\"0.58\",\"NA\",\"0.69\",\"0.54\",\"NA\",\"0.65\",\"0.51\",\"NA\",\"0.52\",\"NA\",\"NA\",\"0.68\",\"0.62\",\"0.83\",\"0.68\",\"0.57\",\"0.62\",\"0.59\",\"0.49\",\"0.50\",\"0.76\",\"0.56\",\"0.65\",\"0.90\",\"NA\",\"0.82\",\"0.57\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.47\",\"0.43\",\"0.42\",\"0.75\",\"NA\",\"NA\",\"NA\",\"0.58\",\"0.49\",\"NA\",\"0.87\",\"NA\",\"NA\",\"0.47\",\"0.59\",\"0.60\",\"0.62\",\"NA\",\"NA\",\"NA\",\"0.51\",\"0.48\",\"0.72\",\"NA\",\"0.79\",\"NA\",\"0.93\",\"0.55\",\"0.67\",\"NA\",\"0.81\",\"NA\",\"0.52\",\"0.54\",\"0.52\",\"NA\",\"0.45\",\"0.49\",\"NA\",\"NA\",\"NA\",\"0.80\",\"0.42\",\"0.55\",\"0.64\",\"0.47\",\"NA\",\"0.61\",\"0.59\",\"NA\",\"NA\",\"0.58\",\"0.69\",\"NA\",\"0.69\",\"0.48\",\"0.45\",\"0.63\",\"0.49\",\"NA\",\"0.49\",\"NA\",\"NA\",\"0.57\",\"NA\",\"0.69\",\"0.68\",\"NA\",\"0.56\",\"0.62\",\"0.46\",\"0.69\",\"0.58\",\"0.67\",\"0.49\",\"NA\",\"0.74\",\"0.60\",\"0.67\",\"0.47\",\"0.54\",\"0.69\",\"NA\",\"0.60\",\"NA\",\"NA\",\"0.48\",\"0.69\",\"0.50\",\"NA\",\"0.49\",\"0.53\",\"0.41\",\"0.72\",\"0.49\",\"NA\",\"0.55\",\"0.84\",\"0.78\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.54\",\"0.56\",\"0.50\",\"NA\",\"NA\",\"0.81\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.61\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.70\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.54\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.66\",\"0.73\",\"NA\",\"NA\",\"0.52\",\"NA\",\"0.91\",\"NA\",\"NA\",\"0.86\",\"0.74\",\"NA\",\"0.49\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.77\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.57\",\"NA\",\"0.57\",\"0.64\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.76\",\"NA\",\"0.61\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.84\",\"NA\",\"NA\",\"0.47\",\"0.75\",\"NA\",\"NA\",\"NA\",\"0.52\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.56\",\"NA\",\"NA\",\"NA\",\"0.75\",\"NA\",\"0.65\",\"NA\",\"NA\",\"0.89\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.65\",\"NA\",\"NA\",\"0.71\",\"0.66\",\"NA\",\"0.47\",\"0.69\",\"0.63\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.56\",\"0.62\",\"0.68\",\"NA\",\"NA\",\"0.58\",\"0.72\",\"NA\",\"0.45\",\"NA\",\"0.63\",\"NA\",\"NA\",\"NA\",\"0.64\",\"0.43\",\"NA\",\"NA\",\"0.51\",\"NA\",\"NA\",\"NA\",\"0.57\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.55\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.55\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.57\",\"0.50\",\"NA\",\"0.75\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.53\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.49\",\"NA\",\"NA\",\"0.56\",\"NA\",\"NA\",\"0.67\",\"NA\",\"NA\",\"0.51\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.40\",\"0.56\",\"NA\",\"0.72\",\"NA\",\"NA\",\"0.47\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.50\",\"0.88\",\"0.88\"],\"peve_context_strength\":[\"1.00\",\"1.02\",\"1.25\",\"1.45\",\"1.17\",\"0.80\",\"1.17\",\"0.92\",\"1.36\",\"0.78\",\"1.10\",\"1.25\",\"1.07\",\"1.25\",\"0.88\",\"1.34\",\"1.20\",\"1.24\",\"0.62\",\"1.05\",\"0.93\",\"0.93\",\"1.08\",\"1.00\",\"1.29\",\"0.93\",\"0.78\",\"1.34\",\"1.26\",\"1.20\",\"0.70\",\"1.02\",\"1.01\",\"1.13\",\"0.65\",\"0.95\",\"1.34\",\"0.90\",\"1.01\",\"0.75\",\"0.88\",\"1.11\",\"0.94\",\"1.30\",\"0.73\",\"0.98\",\"0.84\",\"1.33\",\"0.82\",\"1.00\",\"1.12\",\"1.11\",\"0.93\",\"0.79\",\"1.18\",\"0.86\",\"0.85\",\"0.39\",\"0.93\",\"0.62\",\"0.52\",\"0.64\",\"0.91\",\"0.72\",\"1.37\",\"0.79\",\"0.48\",\"0.73\",\"0.77\",\"1.14\",\"0.44\",\"0.45\",\"0.73\",\"0.82\",\"1.23\",\"0.59\",\"0.63\",\"0.77\",\"1.09\",\"0.46\",\"1.17\",\"0.65\",\"0.85\",\"0.27\",\"0.90\",\"1.03\",\"0.95\",\"1.02\",\"0.39\",\"0.50\",\"0.68\",\"1.09\",\"1.08\",\"0.75\",\"0.75\",\"0.30\",\"0.59\",\"0.47\",\"0.37\",\"0.73\",\"NA\",\"1.52\",\"NA\",\"NA\",\"1.39\",\"1.34\",\"NA\",\"NA\",\"NA\",\"1.32\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.16\",\"NA\",\"NA\",\"1.28\",\"NA\",\"1.22\",\"NA\",\"1.22\",\"NA\",\"NA\",\"1.20\",\"1.11\",\"1.24\",\"NA\",\"NA\",\"1.06\",\"1.22\",\"1.19\",\"NA\",\"1.25\",\"NA\",\"NA\",\"NA\",\"1.19\",\"1.20\",\"NA\",\"1.11\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.07\",\"0.91\",\"0.91\",\"1.18\",\"1.20\",\"1.30\",\"NA\",\"NA\",\"1.13\",\"NA\",\"0.85\",\"1.24\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.97\",\"1.05\",\"1.19\",\"NA\",\"NA\",\"NA\",\"1.18\",\"NA\",\"NA\",\"NA\",\"1.21\",\"NA\",\"1.14\",\"1.03\",\"NA\",\"NA\",\"NA\",\"1.15\",\"1.29\",\"1.04\",\"0.84\",\"1.07\",\"1.08\",\"1.17\",\"0.90\",\"1.04\",\"NA\",\"NA\",\"1.32\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.04\",\"1.20\",\"1.12\",\"NA\",\"0.89\",\"1.13\",\"NA\",\"NA\",\"0.31\",\"NA\",\"NA\",\"NA\",\"0.77\",\"NA\",\"0.92\",\"1.21\",\"NA\",\"NA\",\"0.87\",\"1.15\",\"NA\",\"NA\",\"NA\",\"1.13\",\"NA\",\"1.12\",\"0.45\",\"NA\",\"0.89\",\"0.97\",\"NA\",\"NA\",\"1.20\",\"1.17\",\"NA\",\"0.65\",\"NA\",\"NA\",\"0.92\",\"1.06\",\"0.92\",\"0.79\",\"NA\",\"0.64\",\"NA\",\"NA\",\"NA\",\"0.61\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.67\",\"NA\",\"NA\",\"0.42\",\"0.77\",\"0.80\",\"0.80\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.54\",\"1.03\",\"1.12\",\"1.08\",\"NA\",\"0.55\",\"NA\",\"0.83\",\"0.69\",\"1.15\",\"NA\",\"NA\",\"NA\",\"1.23\",\"0.33\",\"0.66\",\"1.15\",\"NA\",\"NA\",\"0.58\",\"0.86\",\"0.92\",\"0.73\",\"NA\",\"NA\",\"1.01\",\"NA\",\"0.78\",\"NA\",\"NA\",\"1.13\",\"0.68\",\"NA\",\"NA\",\"0.61\",\"0.50\",\"0.78\",\"0.25\",\"NA\",\"NA\",\"0.37\",\"NA\",\"0.89\",\"NA\",\"NA\",\"0.65\",\"0.54\",\"NA\",\"NA\",\"0.29\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.38\",\"NA\",\"0.44\",\"0.53\",\"NA\",\"0.49\",\"NA\",\"0.61\",\"0.85\",\"NA\",\"0.71\",\"0.56\",\"0.99\",\"0.79\",\"NA\",\"NA\",\"0.49\",\"NA\",\"NA\",\"0.79\",\"NA\",\"0.62\",\"NA\",\"0.68\",\"NA\",\"0.53\",\"0.16\",\"0.51\",\"NA\",\"0.48\",\"0.40\",\"0.64\",\"NA\",\"NA\",\"NA\",\"0.53\",\"0.43\",\"0.51\",\"NA\",\"0.07\",\"0.58\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.34\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.31\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.24\",\"1.24\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.23\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.19\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.15\",\"NA\",\"1.15\",\"NA\",\"NA\",\"NA\",\"1.14\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.11\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.06\",\"NA\",\"NA\",\"NA\",\"1.05\",\"NA\",\"NA\",\"1.04\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.01\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.00\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.92\",\"0.92\",\"0.92\",\"NA\",\"NA\",\"0.91\",\"NA\",\"0.90\",\"0.90\",\"0.90\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.85\",\"0.84\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.81\",\"NA\",\"NA\",\"NA\",\"0.75\",\"0.75\",\"NA\",\"0.73\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.65\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.60\",\"0.59\",\"NA\",\"NA\",\"NA\",\"0.54\",\"NA\",\"NA\",\"NA\",\"0.51\",\"NA\",\"0.49\",\"0.48\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.32\",\"NA\",\"NA\",\"NA\"],\"peve_context_dependent\":[false,false,true,false,false,false,false,false,true,false,true,false,false,true,false,true,false,false,true,true,false,false,false,false,true,false,false,true,true,true,true,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,true,true,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,true,true,false,false,true,false,false,true,false,true,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false,null,false,null,null,true,false,null,null,null,true,null,null,null,null,false,null,null,true,null,true,null,false,null,null,true,true,true,null,null,true,false,true,null,false,null,null,null,true,true,null,false,null,null,null,null,null,false,false,false,false,false,false,null,null,true,null,false,false,null,null,null,null,null,false,false,true,null,null,null,false,null,null,null,true,null,false,false,null,null,null,false,false,false,true,false,false,true,false,false,null,null,false,null,null,null,null,true,false,false,null,false,false,null,null,false,null,null,null,false,null,false,false,null,null,false,false,null,null,null,true,null,true,false,null,false,false,null,null,false,false,null,false,null,null,false,false,false,false,null,false,null,null,null,false,null,null,null,null,null,null,null,false,null,null,false,true,false,true,null,null,null,null,false,false,false,true,null,false,null,false,false,true,null,null,null,false,false,false,false,null,null,false,true,true,true,null,null,false,null,false,null,null,true,false,null,null,false,false,false,false,null,null,true,null,false,null,null,false,false,null,null,false,null,null,null,null,null,false,null,false,true,null,false,null,false,true,null,true,false,false,false,null,null,false,null,null,true,null,false,null,false,null,false,false,false,null,false,true,false,null,null,null,false,false,false,null,true,false,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,true,null,null,null,null,null,null,null,null,null,null,false,null,null,null,null,null,null,null,null,null,null,null,null,true,false,null,null,null,null,null,true,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,true,null,null,null,null,null,null,null,null,null,null,null,null,true,null,false,null,null,null,false,null,null,null,null,null,null,null,null,null,false,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,true,null,null,null,false,null,null,false,null,null,null,null,null,null,null,null,null,null,null,false,null,null,null,null,null,null,null,null,null,true,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,false,false,false,null,null,false,null,false,false,false,null,null,null,null,null,null,null,false,true,null,null,null,null,null,null,null,false,null,null,null,false,false,null,false,null,null,null,null,null,null,null,null,null,null,false,null,null,null,null,null,null,false,false,null,null,null,false,null,null,null,false,null,false,false,null,null,null,null,false,null,null,null],\"peve_improvement\":[\"0.03\",\"0.04\",\"0.06\",\"0.03\",\"0.00\",\"0.00\",\"0.02\",\"0.02\",\"0.08\",\"0.02\",\"0.03\",\"0.04\",\"0.01\",\"0.17\",\"0.03\",\"0.06\",\"0.00\",\"0.03\",\"0.08\",\"0.14\",\"0.03\",\"0.00\",\"0.02\",\"0.02\",\"0.08\",\"0.02\",\"0.05\",\"0.13\",\"0.05\",\"0.14\",\"0.06\",\"0.00\",\"0.02\",\"0.12\",\"0.05\",\"0.00\",\"0.13\",\"0.00\",\"0.05\",\"0.02\",\"0.01\",\"0.01\",\"0.01\",\"0.00\",\"0.03\",\"0.01\",\"0.00\",\"0.01\",\"0.01\",\"0.06\",\"0.05\",\"0.02\",\"0.08\",\"0.10\",\"0.02\",\"0.05\",\"0.06\",\"0.00\",\"0.00\",\"0.04\",\"0.00\",\"0.01\",\"0.00\",\"0.08\",\"0.00\",\"0.00\",\"0.00\",\"0.05\",\"0.00\",\"0.08\",\"0.00\",\"0.01\",\"0.02\",\"0.13\",\"0.08\",\"0.01\",\"0.06\",\"0.08\",\"0.00\",\"0.02\",\"0.09\",\"0.00\",\"0.07\",\"0.00\",\"0.01\",\"0.07\",\"0.04\",\"0.00\",\"0.01\",\"0.03\",\"0.00\",\"0.08\",\"0.03\",\"0.00\",\"0.04\",\"0.00\",\"0.01\",\"0.01\",\"0.01\",\"0.04\",\"NA\",\"0.03\",\"NA\",\"NA\",\"0.13\",\"0.05\",\"NA\",\"NA\",\"NA\",\"0.09\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.02\",\"NA\",\"NA\",\"0.07\",\"NA\",\"0.12\",\"NA\",\"0.00\",\"NA\",\"NA\",\"0.09\",\"0.07\",\"0.07\",\"NA\",\"NA\",\"0.15\",\"0.00\",\"0.09\",\"NA\",\"0.03\",\"NA\",\"NA\",\"NA\",\"0.10\",\"0.05\",\"NA\",\"0.01\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.03\",\"0.00\",\"0.04\",\"0.03\",\"0.04\",\"0.00\",\"NA\",\"NA\",\"0.07\",\"NA\",\"0.01\",\"0.01\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.00\",\"0.01\",\"0.07\",\"NA\",\"NA\",\"NA\",\"0.03\",\"NA\",\"NA\",\"NA\",\"0.09\",\"NA\",\"0.03\",\"0.02\",\"NA\",\"NA\",\"NA\",\"0.01\",\"0.01\",\"0.02\",\"0.12\",\"0.00\",\"0.01\",\"0.12\",\"0.06\",\"0.06\",\"NA\",\"NA\",\"0.00\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.04\",\"0.00\",\"0.00\",\"NA\",\"0.00\",\"0.01\",\"NA\",\"NA\",\"0.00\",\"NA\",\"NA\",\"NA\",\"0.00\",\"NA\",\"0.02\",\"0.02\",\"NA\",\"NA\",\"0.01\",\"0.00\",\"NA\",\"NA\",\"NA\",\"0.09\",\"NA\",\"0.07\",\"0.03\",\"NA\",\"0.05\",\"0.00\",\"NA\",\"NA\",\"0.04\",\"0.00\",\"NA\",\"0.04\",\"NA\",\"NA\",\"0.00\",\"0.03\",\"0.02\",\"0.03\",\"NA\",\"0.04\",\"NA\",\"NA\",\"NA\",\"0.01\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.01\",\"NA\",\"NA\",\"0.00\",\"0.12\",\"0.04\",\"0.10\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.02\",\"0.04\",\"0.00\",\"0.08\",\"NA\",\"0.00\",\"NA\",\"0.01\",\"0.01\",\"0.04\",\"NA\",\"NA\",\"NA\",\"0.00\",\"0.01\",\"0.01\",\"0.00\",\"NA\",\"NA\",\"0.06\",\"0.05\",\"0.09\",\"0.06\",\"NA\",\"NA\",\"0.02\",\"NA\",\"0.00\",\"NA\",\"NA\",\"0.04\",\"0.05\",\"NA\",\"NA\",\"0.02\",\"0.01\",\"0.00\",\"0.01\",\"NA\",\"NA\",\"0.05\",\"NA\",\"0.04\",\"NA\",\"NA\",\"0.01\",\"0.02\",\"NA\",\"NA\",\"0.06\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.00\",\"NA\",\"0.01\",\"0.05\",\"NA\",\"0.03\",\"NA\",\"0.07\",\"0.09\",\"NA\",\"0.10\",\"0.01\",\"0.01\",\"0.00\",\"NA\",\"NA\",\"0.00\",\"NA\",\"NA\",\"0.10\",\"NA\",\"0.04\",\"NA\",\"0.02\",\"NA\",\"0.02\",\"0.00\",\"0.01\",\"NA\",\"0.02\",\"0.09\",\"0.00\",\"NA\",\"NA\",\"NA\",\"0.00\",\"0.01\",\"0.01\",\"NA\",\"0.01\",\"0.02\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.05\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.00\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.03\",\"0.02\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.16\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.08\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.09\",\"NA\",\"0.02\",\"NA\",\"NA\",\"NA\",\"0.00\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.00\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.08\",\"NA\",\"NA\",\"NA\",\"0.05\",\"NA\",\"NA\",\"0.00\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.00\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.09\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.01\",\"0.03\",\"0.03\",\"NA\",\"NA\",\"0.04\",\"NA\",\"0.01\",\"0.04\",\"0.03\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.02\",\"0.07\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.00\",\"NA\",\"NA\",\"NA\",\"0.03\",\"0.01\",\"NA\",\"0.01\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.01\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.00\",\"0.01\",\"NA\",\"NA\",\"NA\",\"0.03\",\"NA\",\"NA\",\"NA\",\"0.00\",\"NA\",\"0.04\",\"0.00\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.01\",\"NA\",\"NA\",\"NA\"],\"peve_r2\":[\"0.52\",\"0.49\",\"0.75\",\"0.59\",\"0.68\",\"0.68\",\"0.68\",\"0.59\",\"0.67\",\"0.52\",\"0.80\",\"0.50\",\"0.45\",\"0.84\",\"0.51\",\"0.74\",\"0.65\",\"0.74\",\"0.55\",\"0.67\",\"0.39\",\"0.36\",\"0.72\",\"0.59\",\"0.65\",\"0.76\",\"0.53\",\"0.69\",\"0.73\",\"0.77\",\"0.54\",\"0.55\",\"0.56\",\"0.56\",\"0.49\",\"0.46\",\"0.54\",\"0.32\",\"0.52\",\"0.47\",\"0.43\",\"0.53\",\"0.43\",\"0.64\",\"0.49\",\"0.58\",\"0.37\",\"0.51\",\"0.82\",\"0.55\",\"0.93\",\"0.46\",\"0.44\",\"0.51\",\"0.50\",\"0.42\",\"0.51\",\"0.61\",\"0.39\",\"0.45\",\"0.48\",\"0.45\",\"0.47\",\"0.49\",\"0.55\",\"0.45\",\"0.43\",\"0.45\",\"0.46\",\"0.68\",\"0.48\",\"0.48\",\"0.39\",\"0.55\",\"0.63\",\"0.45\",\"0.48\",\"0.47\",\"0.44\",\"0.43\",\"0.70\",\"0.43\",\"0.55\",\"0.75\",\"0.42\",\"0.69\",\"0.57\",\"0.46\",\"0.44\",\"0.57\",\"0.50\",\"0.68\",\"0.48\",\"0.48\",\"0.43\",\"0.57\",\"0.59\",\"0.39\",\"0.50\",\"0.47\",\"NA\",\"0.45\",\"NA\",\"NA\",\"0.52\",\"0.57\",\"NA\",\"NA\",\"NA\",\"0.70\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.45\",\"NA\",\"NA\",\"0.62\",\"NA\",\"0.60\",\"NA\",\"0.52\",\"NA\",\"NA\",\"0.59\",\"0.99\",\"0.75\",\"NA\",\"NA\",\"0.65\",\"0.57\",\"0.73\",\"NA\",\"0.41\",\"NA\",\"NA\",\"NA\",\"0.59\",\"0.63\",\"NA\",\"0.49\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.61\",\"0.60\",\"0.65\",\"0.61\",\"0.67\",\"0.72\",\"NA\",\"NA\",\"0.51\",\"NA\",\"0.44\",\"0.60\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.72\",\"0.62\",\"0.46\",\"NA\",\"NA\",\"NA\",\"0.55\",\"NA\",\"NA\",\"NA\",\"0.99\",\"NA\",\"0.63\",\"0.48\",\"NA\",\"NA\",\"NA\",\"0.53\",\"0.46\",\"0.74\",\"0.46\",\"0.44\",\"0.61\",\"0.77\",\"0.49\",\"0.54\",\"NA\",\"NA\",\"0.54\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.82\",\"0.59\",\"0.75\",\"NA\",\"0.42\",\"0.73\",\"NA\",\"NA\",\"0.62\",\"NA\",\"NA\",\"NA\",\"0.44\",\"NA\",\"0.52\",\"0.53\",\"NA\",\"NA\",\"0.41\",\"0.47\",\"NA\",\"NA\",\"NA\",\"0.63\",\"NA\",\"0.85\",\"0.45\",\"NA\",\"0.42\",\"0.53\",\"NA\",\"NA\",\"0.68\",\"0.46\",\"NA\",\"0.44\",\"NA\",\"NA\",\"0.41\",\"0.50\",\"0.53\",\"0.45\",\"NA\",\"0.51\",\"NA\",\"NA\",\"NA\",\"0.45\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.38\",\"NA\",\"NA\",\"0.78\",\"0.62\",\"0.44\",\"0.57\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.39\",\"0.47\",\"0.73\",\"0.96\",\"NA\",\"0.46\",\"NA\",\"0.40\",\"0.42\",\"0.73\",\"NA\",\"NA\",\"NA\",\"0.66\",\"0.42\",\"0.53\",\"0.82\",\"NA\",\"NA\",\"0.46\",\"0.75\",\"0.51\",\"0.69\",\"NA\",\"NA\",\"0.47\",\"NA\",\"0.35\",\"NA\",\"NA\",\"0.78\",\"0.50\",\"NA\",\"NA\",\"0.47\",\"0.66\",\"0.47\",\"0.51\",\"NA\",\"NA\",\"0.74\",\"NA\",\"0.51\",\"NA\",\"NA\",\"0.59\",\"0.43\",\"NA\",\"NA\",\"0.45\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.42\",\"NA\",\"0.55\",\"0.71\",\"NA\",\"0.42\",\"NA\",\"0.45\",\"0.51\",\"NA\",\"0.59\",\"0.48\",\"0.58\",\"0.42\",\"NA\",\"NA\",\"0.67\",\"NA\",\"NA\",\"0.53\",\"NA\",\"0.50\",\"NA\",\"0.39\",\"NA\",\"0.43\",\"0.78\",\"0.57\",\"NA\",\"0.39\",\"0.68\",\"0.45\",\"NA\",\"NA\",\"NA\",\"0.53\",\"0.63\",\"0.49\",\"NA\",\"0.93\",\"0.37\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.79\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.39\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.91\",\"0.68\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.79\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.92\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.73\",\"NA\",\"0.46\",\"NA\",\"NA\",\"NA\",\"0.65\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.57\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.65\",\"NA\",\"NA\",\"NA\",\"0.47\",\"NA\",\"NA\",\"0.66\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.69\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.57\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.51\",\"0.41\",\"0.55\",\"NA\",\"NA\",\"0.53\",\"NA\",\"0.44\",\"0.51\",\"0.51\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.39\",\"0.54\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.41\",\"NA\",\"NA\",\"NA\",\"0.42\",\"0.52\",\"NA\",\"0.63\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.59\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.43\",\"0.44\",\"NA\",\"NA\",\"NA\",\"0.46\",\"NA\",\"NA\",\"NA\",\"0.39\",\"NA\",\"0.48\",\"0.57\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.73\",\"NA\",\"NA\",\"NA\"],\"ptua_context_strength\":[\"1.41\",\"1.39\",\"1.49\",\"1.45\",\"1.48\",\"1.61\",\"1.25\",\"1.12\",\"1.19\",\"1.03\",\"1.24\",\"1.23\",\"1.31\",\"1.03\",\"1.37\",\"1.20\",\"0.89\",\"0.99\",\"1.26\",\"1.16\",\"1.61\",\"0.50\",\"1.14\",\"1.50\",\"0.93\",\"1.27\",\"1.21\",\"0.93\",\"1.07\",\"1.20\",\"1.44\",\"0.80\",\"0.79\",\"0.69\",\"1.18\",\"0.90\",\"1.19\",\"1.18\",\"0.88\",\"1.18\",\"1.37\",\"0.73\",\"1.35\",\"0.62\",\"1.35\",\"1.01\",\"1.10\",\"1.15\",\"1.24\",\"1.15\",\"1.03\",\"0.68\",\"0.87\",\"1.16\",\"1.02\",\"1.16\",\"0.95\",\"1.09\",\"1.11\",\"1.42\",\"1.27\",\"1.54\",\"0.85\",\"1.07\",\"0.67\",\"1.10\",\"0.94\",\"0.96\",\"1.18\",\"1.06\",\"1.27\",\"1.22\",\"0.82\",\"0.82\",\"0.53\",\"0.81\",\"1.02\",\"0.87\",\"1.18\",\"1.01\",\"0.71\",\"1.07\",\"0.69\",\"1.24\",\"0.98\",\"0.27\",\"0.46\",\"0.64\",\"0.95\",\"0.85\",\"0.57\",\"0.51\",\"0.36\",\"0.82\",\"1.00\",\"1.04\",\"0.80\",\"0.98\",\"1.08\",\"0.43\",\"1.83\",\"1.50\",\"1.60\",\"1.40\",\"1.51\",\"1.55\",\"1.26\",\"1.63\",\"1.88\",\"1.47\",\"1.32\",\"0.89\",\"1.67\",\"1.49\",\"1.43\",\"1.44\",\"1.24\",\"NA\",\"1.39\",\"1.31\",\"1.50\",\"1.28\",\"1.19\",\"1.31\",\"1.28\",\"1.37\",\"1.21\",\"1.57\",\"1.43\",\"NA\",\"NA\",\"1.21\",\"0.88\",\"1.14\",\"1.51\",\"1.19\",\"1.24\",\"1.17\",\"1.16\",\"1.16\",\"NA\",\"1.29\",\"1.51\",\"1.22\",\"1.47\",\"1.36\",\"1.25\",\"1.40\",\"1.40\",\"1.13\",\"1.10\",\"1.00\",\"1.11\",\"0.78\",\"1.14\",\"1.10\",\"1.41\",\"NA\",\"0.69\",\"0.99\",\"0.96\",\"1.23\",\"1.43\",\"1.27\",\"NA\",\"1.05\",\"1.03\",\"0.93\",\"1.50\",\"NA\",\"1.06\",\"0.81\",\"1.03\",\"1.00\",\"1.19\",\"1.08\",\"1.17\",\"1.04\",\"1.23\",\"1.09\",\"1.03\",\"NA\",\"NA\",\"1.32\",\"NA\",\"1.06\",\"NA\",\"1.24\",\"1.08\",\"1.25\",\"1.26\",\"0.79\",\"0.75\",\"0.97\",\"0.85\",\"1.10\",\"NA\",\"0.88\",\"NA\",\"0.93\",\"1.19\",\"NA\",\"0.78\",\"1.23\",\"1.76\",\"1.20\",\"1.37\",\"0.45\",\"1.26\",\"1.50\",\"1.09\",\"0.81\",\"1.28\",\"0.96\",\"1.14\",\"0.86\",\"0.85\",\"0.80\",\"1.00\",\"0.86\",\"1.08\",\"NA\",\"1.53\",\"1.11\",\"1.08\",\"1.00\",\"1.29\",\"0.75\",\"0.74\",\"NA\",\"1.26\",\"1.27\",\"0.91\",\"1.04\",\"0.99\",\"NA\",\"0.98\",\"1.11\",\"0.70\",\"NA\",\"0.77\",\"0.68\",\"0.78\",\"NA\",\"0.46\",\"0.90\",\"0.91\",\"1.21\",\"0.96\",\"1.05\",\"1.32\",\"1.15\",\"1.08\",\"1.07\",\"1.40\",\"1.04\",\"0.99\",\"0.99\",\"0.88\",\"1.29\",\"0.74\",\"1.14\",\"1.25\",\"0.75\",\"0.66\",\"NA\",\"1.04\",\"1.22\",\"0.82\",\"0.93\",\"1.06\",\"NA\",\"0.93\",\"1.08\",\"0.95\",\"0.51\",\"1.41\",\"1.08\",\"NA\",\"1.10\",\"0.67\",\"1.14\",\"NA\",\"0.79\",\"NA\",\"0.71\",\"0.85\",\"0.69\",\"0.58\",\"0.91\",\"0.77\",\"0.74\",\"NA\",\"0.99\",\"0.41\",\"1.09\",\"1.05\",\"1.15\",\"0.88\",\"NA\",\"1.07\",\"1.04\",\"NA\",\"0.85\",\"0.73\",\"0.69\",\"1.17\",\"0.97\",\"1.08\",\"0.62\",\"0.68\",\"1.31\",\"1.10\",\"1.10\",\"0.69\",\"0.67\",\"0.81\",\"1.19\",\"0.81\",\"1.10\",\"1.00\",\"0.89\",\"1.03\",\"0.74\",\"NA\",\"0.65\",\"0.80\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.41\",\"0.75\",\"0.94\",\"0.85\",\"1.00\",\"NA\",\"0.54\",\"NA\",\"1.06\",\"0.64\",\"0.67\",\"0.79\",\"1.15\",\"NA\",\"0.78\",\"NA\",\"0.80\",\"NA\",\"0.57\",\"0.75\",\"0.73\",\"NA\",\"0.65\",\"NA\",\"0.94\",\"NA\",\"0.39\",\"1.88\",\"1.87\",\"1.84\",\"1.63\",\"1.59\",\"1.53\",\"1.53\",\"1.51\",\"1.48\",\"NA\",\"NA\",\"NA\",\"1.44\",\"1.43\",\"NA\",\"1.39\",\"1.38\",\"1.38\",\"1.38\",\"1.37\",\"1.37\",\"1.37\",\"NA\",\"1.36\",\"1.36\",\"1.36\",\"1.35\",\"1.35\",\"NA\",\"1.34\",\"1.34\",\"1.33\",\"1.33\",\"1.33\",\"1.32\",\"1.32\",\"1.32\",\"1.31\",\"1.31\",\"NA\",\"1.31\",\"NA\",\"1.30\",\"1.30\",\"1.29\",\"1.28\",\"NA\",\"1.28\",\"1.27\",\"1.27\",\"1.26\",\"1.25\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.24\",\"1.24\",\"NA\",\"NA\",\"NA\",\"1.21\",\"1.21\",\"NA\",\"NA\",\"1.21\",\"NA\",\"1.21\",\"1.20\",\"1.20\",\"1.20\",\"NA\",\"1.20\",\"1.20\",\"1.20\",\"NA\",\"NA\",\"1.19\",\"NA\",\"NA\",\"1.18\",\"1.17\",\"1.17\",\"1.17\",\"NA\",\"1.16\",\"NA\",\"1.16\",\"NA\",\"1.15\",\"NA\",\"1.15\",\"NA\",\"1.14\",\"NA\",\"NA\",\"NA\",\"1.13\",\"1.13\",\"1.13\",\"NA\",\"1.12\",\"1.12\",\"1.11\",\"NA\",\"NA\",\"1.11\",\"1.11\",\"1.10\",\"NA\",\"1.09\",\"NA\",\"1.09\",\"1.08\",\"NA\",\"1.08\",\"1.07\",\"1.07\",\"1.07\",\"1.07\",\"1.06\",\"1.06\",\"1.06\",\"1.06\",\"1.06\",\"NA\",\"1.06\",\"1.05\",\"1.05\",\"NA\",\"1.05\",\"1.04\",\"NA\",\"1.03\",\"1.03\",\"1.03\",\"1.03\",\"1.03\",\"1.02\",\"NA\",\"1.02\",\"1.02\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"1.01\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"NA\",\"0.99\",\"0.99\",\"0.99\",\"0.99\",\"0.98\",\"0.98\",\"0.97\",\"NA\",\"NA\",\"NA\",\"0.96\",\"0.96\",\"NA\",\"NA\",\"0.96\",\"NA\",\"0.96\",\"NA\",\"0.95\",\"0.95\",\"0.94\",\"NA\",\"NA\",\"0.93\",\"0.93\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.92\",\"NA\",\"0.91\",\"NA\",\"NA\",\"NA\",\"0.89\",\"0.88\",\"NA\",\"0.86\",\"0.85\",\"0.85\",\"0.85\",\"NA\",\"NA\",\"NA\",\"0.82\",\"0.82\",\"0.82\",\"0.82\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.76\",\"0.76\",\"NA\",\"NA\",\"0.74\",\"NA\",\"NA\",\"0.72\",\"0.72\",\"0.71\",\"0.70\",\"NA\",\"0.68\",\"0.67\",\"NA\",\"0.66\",\"NA\",\"NA\",\"0.63\",\"0.62\",\"NA\",\"0.61\",\"0.61\",\"NA\",\"NA\",\"0.59\",\"0.58\",\"0.55\",\"NA\",\"0.53\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.47\",\"0.46\",\"0.33\",\"NA\",\"NA\",\"NA\",\"NA\"],\"ptua_context_dependent\":[false,true,true,false,false,false,true,false,true,true,false,true,true,true,false,true,true,false,false,true,false,true,true,true,false,false,true,false,false,false,true,false,false,true,false,false,false,true,false,false,false,false,false,false,false,true,false,true,false,true,true,false,false,false,true,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,true,true,false,false,false,false,true,false,true,false,true,true,false,true,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,true,true,true,false,false,false,false,true,true,true,true,false,false,false,true,false,null,false,false,false,true,true,true,false,true,false,false,false,null,null,false,true,true,false,true,true,false,false,true,null,true,false,true,false,false,true,true,false,true,false,true,true,false,true,false,true,null,false,false,true,true,false,true,null,false,false,false,false,null,false,false,false,false,false,true,false,false,true,false,false,null,null,true,null,false,null,false,true,true,true,true,false,false,false,true,null,false,null,false,false,null,false,false,false,true,true,true,false,false,false,false,false,false,false,true,false,true,true,false,true,null,false,false,false,false,false,false,true,null,true,true,false,false,false,null,false,false,false,null,false,false,true,null,false,false,false,true,false,true,true,true,false,false,false,false,true,true,false,true,false,false,false,false,false,null,false,false,false,false,false,null,true,true,false,true,true,false,null,false,true,false,null,false,null,false,true,false,false,true,false,false,null,true,false,false,true,false,false,null,false,false,null,false,false,false,true,false,false,true,false,true,false,true,false,false,false,false,false,false,false,false,true,false,null,true,false,null,null,null,null,false,false,false,false,false,null,false,null,false,false,false,false,false,null,false,null,true,null,false,false,false,null,false,null,false,null,false,false,false,false,false,false,false,true,true,true,null,null,null,true,true,null,false,true,true,false,true,true,true,null,true,false,false,false,true,null,true,true,true,true,false,true,false,false,false,false,null,true,null,true,false,false,false,null,true,true,true,false,true,null,null,null,null,true,true,null,null,null,false,true,null,null,false,null,true,false,false,true,null,true,false,false,null,null,true,null,null,false,false,false,false,null,true,null,false,null,false,null,false,null,false,null,null,null,true,false,false,null,false,true,false,null,null,true,false,false,null,false,null,true,false,null,true,false,false,false,false,false,true,true,false,true,null,false,true,false,null,false,false,null,false,false,true,true,false,false,null,false,true,null,null,null,null,null,null,true,true,true,true,false,true,null,true,false,false,false,false,false,false,null,null,null,true,false,null,null,false,null,true,null,false,false,false,null,null,false,false,null,null,null,null,null,false,null,true,null,null,null,false,false,null,false,false,false,true,null,null,null,true,false,false,false,null,null,null,null,false,false,null,null,false,null,null,false,false,false,false,null,false,false,null,false,null,null,false,false,null,false,false,null,null,false,false,false,null,false,null,null,null,null,null,null,null,false,false,false,null,null,null,null],\"ptua_improvement\":[\"0.03\",\"0.06\",\"0.11\",\"0.00\",\"0.01\",\"0.06\",\"0.11\",\"0.00\",\"0.13\",\"0.10\",\"0.00\",\"0.05\",\"0.14\",\"0.10\",\"0.03\",\"0.04\",\"0.12\",\"0.00\",\"0.00\",\"0.08\",\"0.06\",\"0.08\",\"0.09\",\"0.15\",\"0.03\",\"0.00\",\"0.10\",\"0.02\",\"0.01\",\"0.02\",\"0.14\",\"0.01\",\"0.02\",\"0.08\",\"0.06\",\"0.00\",\"0.01\",\"0.08\",\"0.01\",\"0.02\",\"0.04\",\"0.00\",\"0.03\",\"0.00\",\"0.06\",\"0.20\",\"0.01\",\"0.07\",\"0.00\",\"0.06\",\"0.07\",\"0.03\",\"0.01\",\"0.04\",\"0.06\",\"0.01\",\"0.02\",\"0.00\",\"0.01\",\"0.02\",\"0.05\",\"0.01\",\"0.03\",\"0.07\",\"0.02\",\"0.00\",\"0.02\",\"0.04\",\"0.00\",\"0.04\",\"0.07\",\"0.12\",\"0.01\",\"0.01\",\"0.00\",\"0.00\",\"0.08\",\"0.00\",\"0.15\",\"0.05\",\"0.13\",\"0.08\",\"0.05\",\"0.18\",\"0.01\",\"0.02\",\"0.01\",\"0.02\",\"0.00\",\"0.05\",\"0.04\",\"0.00\",\"0.05\",\"0.13\",\"0.09\",\"0.00\",\"0.00\",\"0.02\",\"0.01\",\"0.01\",\"0.00\",\"0.09\",\"0.34\",\"0.08\",\"0.05\",\"0.01\",\"0.02\",\"0.03\",\"0.06\",\"0.13\",\"0.18\",\"0.06\",\"0.04\",\"0.01\",\"0.02\",\"0.12\",\"0.02\",\"NA\",\"0.04\",\"0.00\",\"0.00\",\"0.06\",\"0.10\",\"0.10\",\"0.00\",\"0.17\",\"0.01\",\"0.00\",\"0.06\",\"NA\",\"NA\",\"0.04\",\"0.09\",\"0.10\",\"0.00\",\"0.18\",\"0.11\",\"0.03\",\"0.02\",\"0.08\",\"NA\",\"0.09\",\"0.03\",\"0.11\",\"0.02\",\"0.02\",\"0.09\",\"0.07\",\"0.02\",\"0.08\",\"0.01\",\"0.09\",\"0.07\",\"0.01\",\"0.15\",\"0.03\",\"0.06\",\"NA\",\"0.02\",\"0.02\",\"0.10\",\"0.21\",\"0.01\",\"0.10\",\"NA\",\"0.04\",\"0.05\",\"0.00\",\"0.04\",\"NA\",\"0.03\",\"0.01\",\"0.01\",\"0.05\",\"0.03\",\"0.05\",\"0.02\",\"0.04\",\"0.20\",\"0.00\",\"0.01\",\"NA\",\"NA\",\"0.14\",\"NA\",\"0.01\",\"NA\",\"0.03\",\"0.07\",\"0.09\",\"0.09\",\"0.08\",\"0.02\",\"0.00\",\"0.02\",\"0.07\",\"NA\",\"0.00\",\"NA\",\"0.03\",\"0.03\",\"NA\",\"0.03\",\"0.00\",\"0.01\",\"0.07\",\"0.24\",\"0.06\",\"0.03\",\"0.02\",\"0.02\",\"0.01\",\"0.01\",\"0.06\",\"0.04\",\"0.12\",\"0.01\",\"0.09\",\"0.18\",\"0.01\",\"0.08\",\"NA\",\"0.01\",\"0.03\",\"0.01\",\"0.01\",\"0.04\",\"0.01\",\"0.08\",\"NA\",\"0.06\",\"0.19\",\"0.04\",\"0.03\",\"0.01\",\"NA\",\"0.01\",\"0.04\",\"0.01\",\"NA\",\"0.04\",\"0.00\",\"0.06\",\"NA\",\"0.01\",\"0.00\",\"0.03\",\"0.05\",\"0.03\",\"0.14\",\"0.08\",\"0.13\",\"0.03\",\"0.05\",\"0.00\",\"0.03\",\"0.12\",\"0.09\",\"0.03\",\"0.05\",\"0.02\",\"0.05\",\"0.00\",\"0.02\",\"0.01\",\"NA\",\"0.04\",\"0.02\",\"0.03\",\"0.01\",\"0.05\",\"NA\",\"0.19\",\"0.13\",\"0.00\",\"0.04\",\"0.12\",\"0.01\",\"NA\",\"0.01\",\"0.08\",\"0.04\",\"NA\",\"0.01\",\"NA\",\"0.02\",\"0.07\",\"0.01\",\"0.00\",\"0.08\",\"0.02\",\"0.03\",\"NA\",\"0.11\",\"0.04\",\"0.02\",\"0.10\",\"0.05\",\"0.05\",\"NA\",\"0.02\",\"0.03\",\"NA\",\"0.02\",\"0.03\",\"0.05\",\"0.21\",\"0.02\",\"0.03\",\"0.06\",\"0.00\",\"0.12\",\"0.00\",\"0.13\",\"0.00\",\"0.00\",\"0.01\",\"0.03\",\"0.00\",\"0.01\",\"0.02\",\"0.01\",\"0.14\",\"0.01\",\"NA\",\"0.11\",\"0.00\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.02\",\"0.00\",\"0.03\",\"0.02\",\"0.03\",\"NA\",\"0.00\",\"NA\",\"0.05\",\"0.01\",\"0.06\",\"0.04\",\"0.00\",\"NA\",\"0.00\",\"NA\",\"0.08\",\"NA\",\"0.01\",\"0.02\",\"0.02\",\"NA\",\"0.05\",\"NA\",\"0.01\",\"NA\",\"0.02\",\"0.02\",\"0.02\",\"0.00\",\"0.02\",\"0.01\",\"0.06\",\"0.18\",\"0.11\",\"0.23\",\"NA\",\"NA\",\"NA\",\"0.07\",\"0.04\",\"NA\",\"0.04\",\"0.16\",\"0.07\",\"0.03\",\"0.21\",\"0.21\",\"0.05\",\"NA\",\"0.14\",\"0.05\",\"0.03\",\"0.00\",\"0.08\",\"NA\",\"0.10\",\"0.11\",\"0.03\",\"0.12\",\"0.00\",\"0.06\",\"0.01\",\"0.00\",\"0.00\",\"0.03\",\"NA\",\"0.15\",\"NA\",\"0.12\",\"0.01\",\"0.05\",\"0.01\",\"NA\",\"0.11\",\"0.15\",\"0.07\",\"0.00\",\"0.06\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.06\",\"0.07\",\"NA\",\"NA\",\"NA\",\"0.05\",\"0.11\",\"NA\",\"NA\",\"0.00\",\"NA\",\"0.08\",\"0.04\",\"0.03\",\"0.07\",\"NA\",\"0.17\",\"0.07\",\"0.00\",\"NA\",\"NA\",\"0.14\",\"NA\",\"NA\",\"0.03\",\"0.02\",\"0.03\",\"0.01\",\"NA\",\"0.10\",\"NA\",\"0.01\",\"NA\",\"0.04\",\"NA\",\"0.00\",\"NA\",\"0.01\",\"NA\",\"NA\",\"NA\",\"0.24\",\"0.00\",\"0.03\",\"NA\",\"0.01\",\"0.09\",\"0.05\",\"NA\",\"NA\",\"0.06\",\"0.00\",\"0.03\",\"NA\",\"0.01\",\"NA\",\"0.08\",\"0.01\",\"NA\",\"0.17\",\"0.02\",\"0.01\",\"0.00\",\"0.00\",\"0.02\",\"0.09\",\"0.09\",\"0.03\",\"0.13\",\"NA\",\"0.06\",\"0.20\",\"0.04\",\"NA\",\"0.00\",\"0.04\",\"NA\",\"0.06\",\"0.00\",\"0.14\",\"0.07\",\"0.00\",\"0.01\",\"NA\",\"0.03\",\"0.11\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.13\",\"0.15\",\"0.15\",\"0.07\",\"0.01\",\"0.09\",\"NA\",\"0.16\",\"0.05\",\"0.03\",\"0.02\",\"0.05\",\"0.03\",\"0.00\",\"NA\",\"NA\",\"NA\",\"0.09\",\"0.05\",\"NA\",\"NA\",\"0.01\",\"NA\",\"0.10\",\"NA\",\"0.02\",\"0.05\",\"0.03\",\"NA\",\"NA\",\"0.02\",\"0.03\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.02\",\"NA\",\"0.08\",\"NA\",\"NA\",\"NA\",\"0.02\",\"0.02\",\"NA\",\"0.02\",\"0.00\",\"0.03\",\"0.16\",\"NA\",\"NA\",\"NA\",\"0.07\",\"0.01\",\"0.00\",\"0.04\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.02\",\"0.00\",\"NA\",\"NA\",\"0.01\",\"NA\",\"NA\",\"0.06\",\"0.06\",\"0.01\",\"0.00\",\"NA\",\"0.03\",\"0.05\",\"NA\",\"0.00\",\"NA\",\"NA\",\"0.00\",\"0.00\",\"NA\",\"0.00\",\"0.02\",\"NA\",\"NA\",\"0.01\",\"0.00\",\"0.00\",\"NA\",\"0.01\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.00\",\"0.01\",\"0.00\",\"NA\",\"NA\",\"NA\",\"NA\"],\"ptua_r2\":[\"0.56\",\"0.50\",\"0.55\",\"0.61\",\"0.43\",\"0.46\",\"0.82\",\"0.44\",\"0.63\",\"0.64\",\"0.58\",\"0.76\",\"0.56\",\"0.54\",\"0.38\",\"0.70\",\"0.48\",\"0.62\",\"0.47\",\"0.64\",\"0.50\",\"0.51\",\"0.48\",\"0.54\",\"0.46\",\"0.35\",\"0.59\",\"0.40\",\"0.44\",\"0.44\",\"0.66\",\"0.44\",\"0.44\",\"0.44\",\"0.42\",\"0.47\",\"0.48\",\"0.63\",\"0.45\",\"0.65\",\"0.63\",\"0.30\",\"0.56\",\"0.50\",\"0.48\",\"0.58\",\"0.40\",\"0.46\",\"0.57\",\"0.75\",\"0.53\",\"0.46\",\"0.33\",\"0.49\",\"0.53\",\"0.56\",\"0.40\",\"0.53\",\"0.43\",\"0.45\",\"0.66\",\"0.47\",\"0.36\",\"0.45\",\"0.46\",\"0.55\",\"0.52\",\"0.50\",\"0.59\",\"0.54\",\"0.51\",\"0.56\",\"0.54\",\"0.36\",\"0.46\",\"0.65\",\"0.71\",\"0.54\",\"0.47\",\"0.51\",\"0.50\",\"0.54\",\"0.49\",\"0.74\",\"0.49\",\"0.67\",\"0.47\",\"0.48\",\"0.43\",\"0.49\",\"0.41\",\"0.44\",\"0.45\",\"0.49\",\"0.63\",\"0.38\",\"0.52\",\"0.49\",\"0.55\",\"0.43\",\"0.58\",\"0.78\",\"0.79\",\"0.46\",\"0.51\",\"0.50\",\"0.68\",\"0.67\",\"0.58\",\"0.73\",\"0.68\",\"0.53\",\"0.51\",\"0.69\",\"0.43\",\"0.76\",\"0.59\",\"NA\",\"0.68\",\"0.47\",\"0.52\",\"0.72\",\"0.47\",\"0.66\",\"0.47\",\"0.90\",\"0.38\",\"0.78\",\"0.45\",\"NA\",\"NA\",\"0.42\",\"0.60\",\"0.63\",\"0.61\",\"0.59\",\"0.62\",\"0.43\",\"0.60\",\"0.51\",\"NA\",\"0.54\",\"0.59\",\"0.63\",\"0.39\",\"0.54\",\"0.57\",\"0.50\",\"0.56\",\"0.54\",\"0.59\",\"0.69\",\"0.46\",\"0.40\",\"0.64\",\"0.35\",\"0.93\",\"NA\",\"0.84\",\"0.34\",\"0.51\",\"0.97\",\"0.46\",\"0.70\",\"NA\",\"0.45\",\"0.43\",\"0.47\",\"0.56\",\"NA\",\"0.42\",\"0.37\",\"0.47\",\"0.53\",\"0.45\",\"0.62\",\"0.43\",\"0.59\",\"0.62\",\"0.62\",\"0.47\",\"NA\",\"NA\",\"0.48\",\"NA\",\"0.59\",\"NA\",\"0.56\",\"0.47\",\"0.65\",\"0.63\",\"0.65\",\"0.50\",\"0.56\",\"0.40\",\"0.61\",\"NA\",\"0.62\",\"NA\",\"0.40\",\"0.50\",\"NA\",\"0.55\",\"0.43\",\"0.54\",\"0.82\",\"0.73\",\"0.49\",\"0.39\",\"0.39\",\"0.62\",\"0.47\",\"0.53\",\"0.46\",\"0.48\",\"0.50\",\"0.47\",\"0.45\",\"0.56\",\"0.43\",\"0.55\",\"NA\",\"0.65\",\"0.43\",\"0.51\",\"0.39\",\"0.45\",\"0.51\",\"0.54\",\"NA\",\"0.68\",\"0.78\",\"0.61\",\"0.51\",\"0.62\",\"NA\",\"0.58\",\"0.46\",\"0.49\",\"NA\",\"0.54\",\"0.57\",\"0.58\",\"NA\",\"0.51\",\"0.41\",\"0.47\",\"0.89\",\"0.50\",\"0.52\",\"0.43\",\"0.62\",\"0.45\",\"0.47\",\"0.39\",\"0.49\",\"0.45\",\"0.44\",\"0.46\",\"0.66\",\"0.35\",\"0.42\",\"0.60\",\"0.45\",\"0.45\",\"NA\",\"0.50\",\"0.56\",\"0.40\",\"0.42\",\"0.47\",\"NA\",\"0.75\",\"0.63\",\"0.41\",\"0.76\",\"0.60\",\"0.71\",\"NA\",\"0.57\",\"0.51\",\"0.61\",\"NA\",\"0.58\",\"NA\",\"0.38\",\"0.48\",\"0.59\",\"0.39\",\"0.53\",\"0.48\",\"0.45\",\"NA\",\"0.57\",\"0.48\",\"0.48\",\"0.52\",\"0.41\",\"0.51\",\"NA\",\"0.33\",\"0.51\",\"NA\",\"0.49\",\"0.38\",\"0.57\",\"0.59\",\"0.44\",\"0.40\",\"0.56\",\"0.49\",\"0.82\",\"0.50\",\"0.56\",\"0.38\",\"0.37\",\"0.44\",\"0.49\",\"0.43\",\"0.43\",\"0.41\",\"0.32\",\"0.50\",\"0.39\",\"NA\",\"0.58\",\"0.37\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.50\",\"0.56\",\"0.67\",\"0.44\",\"0.47\",\"NA\",\"0.44\",\"NA\",\"0.51\",\"0.50\",\"0.42\",\"0.49\",\"0.52\",\"NA\",\"0.33\",\"NA\",\"0.58\",\"NA\",\"0.54\",\"0.37\",\"0.40\",\"NA\",\"0.48\",\"NA\",\"0.45\",\"NA\",\"0.69\",\"0.47\",\"0.58\",\"0.74\",\"0.82\",\"0.61\",\"0.44\",\"0.79\",\"0.63\",\"0.84\",\"NA\",\"NA\",\"NA\",\"0.63\",\"0.66\",\"NA\",\"0.68\",\"0.72\",\"0.48\",\"0.66\",\"0.74\",\"0.74\",\"0.79\",\"NA\",\"0.73\",\"0.42\",\"0.51\",\"0.38\",\"0.83\",\"NA\",\"0.52\",\"0.58\",\"0.78\",\"0.71\",\"0.46\",\"0.75\",\"0.42\",\"0.74\",\"0.81\",\"0.48\",\"NA\",\"0.76\",\"NA\",\"0.88\",\"0.69\",\"0.61\",\"0.51\",\"NA\",\"0.66\",\"0.96\",\"0.51\",\"0.69\",\"0.79\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.57\",\"0.45\",\"NA\",\"NA\",\"NA\",\"0.56\",\"0.52\",\"NA\",\"NA\",\"0.57\",\"NA\",\"0.44\",\"0.57\",\"0.44\",\"0.50\",\"NA\",\"0.75\",\"0.37\",\"0.40\",\"NA\",\"NA\",\"0.66\",\"NA\",\"NA\",\"0.41\",\"0.40\",\"0.43\",\"0.59\",\"NA\",\"0.69\",\"NA\",\"0.52\",\"NA\",\"0.47\",\"NA\",\"0.60\",\"NA\",\"0.46\",\"NA\",\"NA\",\"NA\",\"0.72\",\"0.71\",\"0.59\",\"NA\",\"0.54\",\"0.50\",\"0.42\",\"NA\",\"NA\",\"0.52\",\"0.37\",\"0.35\",\"NA\",\"0.65\",\"NA\",\"0.51\",\"0.48\",\"NA\",\"0.63\",\"0.40\",\"0.49\",\"0.64\",\"0.40\",\"0.46\",\"0.42\",\"0.59\",\"0.68\",\"0.60\",\"NA\",\"0.46\",\"0.60\",\"0.45\",\"NA\",\"0.39\",\"0.59\",\"NA\",\"0.42\",\"0.39\",\"0.47\",\"0.65\",\"0.47\",\"0.50\",\"NA\",\"0.40\",\"0.63\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.64\",\"0.51\",\"0.59\",\"0.52\",\"0.35\",\"0.38\",\"NA\",\"0.58\",\"0.51\",\"0.36\",\"0.34\",\"0.46\",\"0.42\",\"0.56\",\"NA\",\"NA\",\"NA\",\"0.40\",\"0.46\",\"NA\",\"NA\",\"0.53\",\"NA\",\"0.51\",\"NA\",\"0.41\",\"0.61\",\"0.67\",\"NA\",\"NA\",\"0.50\",\"0.51\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.40\",\"NA\",\"0.53\",\"NA\",\"NA\",\"NA\",\"0.55\",\"0.51\",\"NA\",\"0.48\",\"0.41\",\"0.59\",\"0.50\",\"NA\",\"NA\",\"NA\",\"0.90\",\"0.52\",\"0.60\",\"0.41\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.48\",\"0.35\",\"NA\",\"NA\",\"0.42\",\"NA\",\"NA\",\"0.43\",\"0.43\",\"0.48\",\"0.40\",\"NA\",\"0.55\",\"0.44\",\"NA\",\"0.42\",\"NA\",\"NA\",\"0.40\",\"0.47\",\"NA\",\"0.56\",\"0.41\",\"NA\",\"NA\",\"0.61\",\"0.48\",\"0.36\",\"NA\",\"0.45\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"0.39\",\"0.51\",\"0.66\",\"NA\",\"NA\",\"NA\",\"NA\"],\"mean_context_strength\":[\"1.31\",\"1.30\",\"1.24\",\"1.24\",\"1.20\",\"1.20\",\"1.19\",\"1.19\",\"1.17\",\"1.16\",\"1.16\",\"1.14\",\"1.13\",\"1.12\",\"1.11\",\"1.11\",\"1.11\",\"1.10\",\"1.08\",\"1.07\",\"1.07\",\"1.07\",\"1.07\",\"1.07\",\"1.06\",\"1.06\",\"1.06\",\"1.06\",\"1.06\",\"1.05\",\"1.04\",\"1.04\",\"1.03\",\"1.02\",\"1.01\",\"1.01\",\"1.01\",\"1.00\",\"0.99\",\"0.99\",\"0.99\",\"0.98\",\"0.97\",\"0.97\",\"0.96\",\"0.96\",\"0.96\",\"0.96\",\"0.96\",\"0.95\",\"0.94\",\"0.94\",\"0.94\",\"0.94\",\"0.94\",\"0.93\",\"0.93\",\"0.93\",\"0.92\",\"0.92\",\"0.92\",\"0.92\",\"0.91\",\"0.91\",\"0.90\",\"0.90\",\"0.90\",\"0.89\",\"0.88\",\"0.87\",\"0.87\",\"0.86\",\"0.86\",\"0.86\",\"0.86\",\"0.84\",\"0.84\",\"0.84\",\"0.84\",\"0.84\",\"0.84\",\"0.81\",\"0.81\",\"0.80\",\"0.80\",\"0.79\",\"0.78\",\"0.77\",\"0.76\",\"0.75\",\"0.75\",\"0.74\",\"0.72\",\"0.71\",\"0.69\",\"0.69\",\"0.69\",\"0.62\",\"0.62\",\"0.58\",\"1.55\",\"1.51\",\"1.49\",\"1.48\",\"1.45\",\"1.44\",\"1.42\",\"1.41\",\"1.40\",\"1.39\",\"1.38\",\"1.35\",\"1.34\",\"1.31\",\"1.30\",\"1.30\",\"1.29\",\"1.28\",\"1.27\",\"1.27\",\"1.26\",\"1.25\",\"1.25\",\"1.25\",\"1.24\",\"1.24\",\"1.22\",\"1.22\",\"1.22\",\"1.21\",\"1.20\",\"1.20\",\"1.20\",\"1.20\",\"1.20\",\"1.19\",\"1.18\",\"1.18\",\"1.18\",\"1.18\",\"1.17\",\"1.17\",\"1.17\",\"1.17\",\"1.16\",\"1.16\",\"1.16\",\"1.16\",\"1.15\",\"1.15\",\"1.15\",\"1.15\",\"1.15\",\"1.14\",\"1.14\",\"1.14\",\"1.13\",\"1.13\",\"1.13\",\"1.13\",\"1.13\",\"1.13\",\"1.12\",\"1.12\",\"1.12\",\"1.12\",\"1.12\",\"1.12\",\"1.12\",\"1.12\",\"1.12\",\"1.11\",\"1.11\",\"1.11\",\"1.11\",\"1.11\",\"1.10\",\"1.10\",\"1.10\",\"1.09\",\"1.09\",\"1.09\",\"1.08\",\"1.08\",\"1.07\",\"1.07\",\"1.07\",\"1.07\",\"1.06\",\"1.06\",\"1.06\",\"1.06\",\"1.06\",\"1.05\",\"1.05\",\"1.04\",\"1.04\",\"1.04\",\"1.04\",\"1.04\",\"1.04\",\"1.04\",\"1.04\",\"1.04\",\"1.04\",\"1.03\",\"1.03\",\"1.02\",\"1.02\",\"1.01\",\"1.01\",\"1.01\",\"1.01\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"0.99\",\"0.99\",\"0.99\",\"0.99\",\"0.99\",\"0.98\",\"0.98\",\"0.98\",\"0.98\",\"0.97\",\"0.96\",\"0.96\",\"0.96\",\"0.96\",\"0.96\",\"0.96\",\"0.95\",\"0.95\",\"0.95\",\"0.95\",\"0.95\",\"0.94\",\"0.94\",\"0.93\",\"0.93\",\"0.93\",\"0.93\",\"0.92\",\"0.92\",\"0.92\",\"0.92\",\"0.91\",\"0.91\",\"0.91\",\"0.91\",\"0.91\",\"0.91\",\"0.90\",\"0.90\",\"0.90\",\"0.90\",\"0.89\",\"0.89\",\"0.89\",\"0.89\",\"0.89\",\"0.89\",\"0.89\",\"0.88\",\"0.88\",\"0.88\",\"0.88\",\"0.88\",\"0.87\",\"0.87\",\"0.87\",\"0.87\",\"0.87\",\"0.87\",\"0.86\",\"0.86\",\"0.86\",\"0.86\",\"0.86\",\"0.85\",\"0.85\",\"0.85\",\"0.85\",\"0.85\",\"0.85\",\"0.85\",\"0.84\",\"0.84\",\"0.84\",\"0.84\",\"0.83\",\"0.83\",\"0.83\",\"0.83\",\"0.83\",\"0.82\",\"0.82\",\"0.82\",\"0.82\",\"0.81\",\"0.81\",\"0.81\",\"0.81\",\"0.81\",\"0.81\",\"0.80\",\"0.80\",\"0.80\",\"0.80\",\"0.80\",\"0.79\",\"0.79\",\"0.79\",\"0.79\",\"0.78\",\"0.77\",\"0.76\",\"0.76\",\"0.76\",\"0.76\",\"0.75\",\"0.75\",\"0.75\",\"0.74\",\"0.74\",\"0.73\",\"0.72\",\"0.72\",\"0.72\",\"0.72\",\"0.71\",\"0.71\",\"0.69\",\"0.69\",\"0.68\",\"0.67\",\"0.66\",\"0.66\",\"0.66\",\"0.65\",\"0.64\",\"0.63\",\"0.60\",\"0.60\",\"0.59\",\"0.59\",\"0.58\",\"0.56\",\"0.55\",\"0.54\",\"0.52\",\"0.52\",\"0.51\",\"0.49\",\"1.88\",\"1.87\",\"1.84\",\"1.63\",\"1.59\",\"1.53\",\"1.53\",\"1.51\",\"1.48\",\"1.48\",\"1.47\",\"1.44\",\"1.44\",\"1.43\",\"1.40\",\"1.39\",\"1.38\",\"1.38\",\"1.38\",\"1.37\",\"1.37\",\"1.37\",\"1.37\",\"1.36\",\"1.36\",\"1.36\",\"1.35\",\"1.35\",\"1.34\",\"1.34\",\"1.34\",\"1.33\",\"1.33\",\"1.33\",\"1.32\",\"1.32\",\"1.32\",\"1.31\",\"1.31\",\"1.31\",\"1.31\",\"1.30\",\"1.30\",\"1.30\",\"1.29\",\"1.28\",\"1.28\",\"1.28\",\"1.27\",\"1.27\",\"1.26\",\"1.25\",\"1.24\",\"1.24\",\"1.24\",\"1.24\",\"1.24\",\"1.24\",\"1.23\",\"1.23\",\"1.23\",\"1.21\",\"1.21\",\"1.21\",\"1.21\",\"1.21\",\"1.21\",\"1.21\",\"1.20\",\"1.20\",\"1.20\",\"1.20\",\"1.20\",\"1.20\",\"1.20\",\"1.19\",\"1.19\",\"1.19\",\"1.19\",\"1.18\",\"1.18\",\"1.17\",\"1.17\",\"1.17\",\"1.16\",\"1.16\",\"1.16\",\"1.16\",\"1.15\",\"1.15\",\"1.15\",\"1.15\",\"1.14\",\"1.14\",\"1.14\",\"1.14\",\"1.13\",\"1.13\",\"1.13\",\"1.13\",\"1.13\",\"1.12\",\"1.12\",\"1.11\",\"1.11\",\"1.11\",\"1.11\",\"1.11\",\"1.10\",\"1.10\",\"1.09\",\"1.09\",\"1.09\",\"1.08\",\"1.08\",\"1.08\",\"1.07\",\"1.07\",\"1.07\",\"1.07\",\"1.06\",\"1.06\",\"1.06\",\"1.06\",\"1.06\",\"1.06\",\"1.06\",\"1.05\",\"1.05\",\"1.05\",\"1.05\",\"1.04\",\"1.04\",\"1.03\",\"1.03\",\"1.03\",\"1.03\",\"1.03\",\"1.02\",\"1.02\",\"1.02\",\"1.02\",\"1.01\",\"1.01\",\"1.01\",\"1.01\",\"1.01\",\"1.01\",\"1.01\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"1.00\",\"0.99\",\"0.99\",\"0.99\",\"0.99\",\"0.98\",\"0.98\",\"0.97\",\"0.97\",\"0.97\",\"0.96\",\"0.96\",\"0.96\",\"0.96\",\"0.96\",\"0.96\",\"0.96\",\"0.96\",\"0.95\",\"0.95\",\"0.95\",\"0.94\",\"0.94\",\"0.94\",\"0.93\",\"0.93\",\"0.93\",\"0.92\",\"0.92\",\"0.92\",\"0.92\",\"0.92\",\"0.91\",\"0.91\",\"0.90\",\"0.90\",\"0.90\",\"0.89\",\"0.88\",\"0.88\",\"0.86\",\"0.85\",\"0.85\",\"0.85\",\"0.85\",\"0.84\",\"0.83\",\"0.82\",\"0.82\",\"0.82\",\"0.82\",\"0.81\",\"0.81\",\"0.81\",\"0.80\",\"0.76\",\"0.76\",\"0.75\",\"0.75\",\"0.74\",\"0.73\",\"0.72\",\"0.72\",\"0.72\",\"0.71\",\"0.70\",\"0.70\",\"0.68\",\"0.67\",\"0.66\",\"0.66\",\"0.65\",\"0.64\",\"0.63\",\"0.62\",\"0.61\",\"0.61\",\"0.61\",\"0.60\",\"0.59\",\"0.59\",\"0.58\",\"0.55\",\"0.54\",\"0.53\",\"0.51\",\"0.51\",\"0.51\",\"0.51\",\"0.49\",\"0.48\",\"0.48\",\"0.47\",\"0.46\",\"0.33\",\"0.32\",\"0.32\",\"0.27\",\"0.14\"]},\"columns\":[{\"id\":\"og_id\",\"name\":\"og_id\",\"type\":\"character\"},{\"id\":\"n_species\",\"name\":\"n_species\",\"type\":\"character\"},{\"id\":\"apul_context_strength\",\"name\":\"apul_context_strength\",\"type\":\"character\"},{\"id\":\"apul_context_dependent\",\"name\":\"apul_context_dependent\",\"type\":\"logical\"},{\"id\":\"apul_improvement\",\"name\":\"apul_improvement\",\"type\":\"character\"},{\"id\":\"apul_r2\",\"name\":\"apul_r2\",\"type\":\"character\"},{\"id\":\"peve_context_strength\",\"name\":\"peve_context_strength\",\"type\":\"character\"},{\"id\":\"peve_context_dependent\",\"name\":\"peve_context_dependent\",\"type\":\"logical\"},{\"id\":\"peve_improvement\",\"name\":\"peve_improvement\",\"type\":\"character\"},{\"id\":\"peve_r2\",\"name\":\"peve_r2\",\"type\":\"character\"},{\"id\":\"ptua_context_strength\",\"name\":\"ptua_context_strength\",\"type\":\"character\"},{\"id\":\"ptua_context_dependent\",\"name\":\"ptua_context_dependent\",\"type\":\"logical\"},{\"id\":\"ptua_improvement\",\"name\":\"ptua_improvement\",\"type\":\"character\"},{\"id\":\"ptua_r2\",\"name\":\"ptua_r2\",\"type\":\"character\"},{\"id\":\"mean_context_strength\",\"name\":\"mean_context_strength\",\"type\":\"character\"}],\"filterable\":true,\"searchable\":true,\"defaultPageSize\":20,\"highlight\":true,\"striped\":true,\"theme\":{\"highlightColor\":\"#EAF2F8\"},\"dataKey\":\"ce6bba268a40618e309dde535081d2dc\"},\"children\":[]},\"class\":\"reactR_markup\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n# Full on, Statiscal Robust ConTra\n\n```\nsr320@n3439:/mmfs1/gscratch/scrubbed/sr320/github/ConTra$ python code/context_dependent_analysis.py   --data-dir data/full-species-biomin/cleaned_peve   --enable-empirical-fdr   --null-replicates 1   --fdr-alpha 0.3   --enable-lncrna-context   --enable-multi-way\n🚀 Initializing optimized context-dependent analysis with 192 parallel workers\n💾 Available RAM: 2963.0 GB\n📁 Output directory: /mmfs1/gscratch/scrubbed/sr320/github/ConTra/output/context_dependent_analysis_20251130_091333\n📂 Loading cleaned datasets with parallel processing...\n✅ Loaded gene expression: (553, 36)\n✅ Loaded lncRNA expression: (8319, 36)\n✅ Loaded miRNA expression: (48, 36)\n✅ Loaded DNA methylation: (104459, 36)\n✓ All datasets aligned with 36 samples\nTime points: ['TP1', 'TP2', 'TP3', 'TP4']\nConditions: ['216', '236', '245', '260', '262', '69', '72', '73', '74', '83']\n```\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/core-js-2.5.3/shim.min.js\"></script>\n<script src=\"../../site_libs/react-18.2.0/react.min.js\"></script>\n<script src=\"../../site_libs/react-18.2.0/react-dom.min.js\"></script>\n<script src=\"../../site_libs/reactwidget-2.0.0/react-tools.js\"></script>\n<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/reactable-0.4.4/reactable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/reactable-binding-0.4.4/reactable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}