name: Email Notes to GitHub (Insert Below YAML)

on:
  repository_dispatch:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  append_notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate GitHub CLI
        run: |
          git config --global user.email "sr320@uw.edu"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/sr320/tumbling-oysters.git

      - name: Insert note below YAML header
        run: |
          FILE="notes.qmd"
          NOTE="${{ github.event.client_payload.note }}"
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

          # Find the end of YAML header (--- separator)
          YAML_LINE=$(awk '/^---$/ {count++; if (count == 2) {print NR; exit}}' "$FILE")

          # Insert the note after the YAML header
          awk -v line=$YAML_LINE -v text="\n## Note ($TIMESTAMP)\n\n$NOTE\n\n" '
          {print} NR == line {print text}
          ' "$FILE" > temp.qmd && mv temp.qmd "$FILE"

      - name: Commit and push changes
        run: |
          git add notes.qmd
          git commit -m "Added new note from email" || echo "No changes to commit"
          git push origin main
