name: Email Notes to GitHub (Insert Below YAML & Render Quarto)

on:
  repository_dispatch:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  append_notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Ensures it does not use default GitHub Actions token

      - name: Authenticate GitHub CLI
        run: |
          git config --global user.email "sr320@uw.edu"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/sr320/tumbling-oysters.git

      - name: Insert note below YAML header
        run: |
          FILE="notes.qmd"
          NOTE="${{ github.event.client_payload.note }}"

          # Set timezone to Pacific Time (PST/PDT depending on daylight saving)
          export TZ="America/Los_Angeles"
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

          # Find the end of YAML header (--- separator)
          YAML_LINE=$(awk '/^---$/ {count++; if (count == 2) {print NR; exit}}' "$FILE")

          # Insert the note after the YAML header
          awk -v line="$YAML_LINE" -v text="\n## Note (${TIMESTAMP})\n\n${NOTE}\n\n" '
          {print} NR == line {print text}
          ' "$FILE" > temp.qmd && mv temp.qmd "$FILE"

      - name: Install R
        run: |
          sudo apt update
          sudo apt install -y r-base

      - name: Install Quarto
        run: |
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.450/quarto-1.3.450-linux-amd64.deb
          sudo dpkg -i quarto-1.3.450-linux-amd64.deb
          rm quarto-1.3.450-linux-amd64.deb
          quarto --version

      - name: Install R Packages in User-Writable Directory
        run: |
          mkdir -p ~/R/library
          echo 'R_LIBS_USER="~/R/library"' >> ~/.Renviron
          Rscript -e 'install.packages(c("rmarkdown", "knitr"), repos="http://cran.rstudio.com/", lib="~/R/library")'

      - name: Render Quarto document to `docs/`
        env:
          R_LIBS_USER: ~/R/library
        run: |
          mkdir -p docs
          quarto render notes.qmd --to html --output-dir docs

      - name: Commit and Push Changes
        run: |
          git add notes.qmd
          [ -f docs/notes.html ] && git add docs/notes.html  # Only add if it exists
          git commit -m "Added new note from email and rendered Quarto to docs/" || echo "No changes to commit"
          git push origin main
